Update emojis
Chatterino/chatterino2 pull request #1555
Opened 2020-02-15 17:04 UTC by pajlada

The plan is to:
 - [ ] Update the emoji stuff to support Unicode 12.1 emojis and their new tone stuff
 - [ ] Upload emojis to a proper CDN instead of using a random server

2020-02-23 14:54 UTC, RAnders00 commented
https://www.jsdelivr.com/package/npm/emoji-datasource-twitter?path=img%2Ftwitter%2F64 twitter emojis are on jsdelivr too as far as i can see

2020-02-23 21:15 UTC, RAnders00 commented
An issue I've found: Some modifiers are not rendered as images when there are images for them, for example 🦲 (EMOJI COMPONENT BALD) renders as https://abs-0.twimg.com/emoji/v2/svg/1f9b2.svg when used on twitter.com (used as a reference for their Twitter set of emoji images) however in chatterino it does not render: 
![image](https://user-images.githubusercontent.com/1629196/75120199-f0484d80-5689-11ea-9759-2802562792db.png)

Emojipedia also lists the twitter image for the "bald" modifier alone: https://emojipedia.org/bald/
![image](https://user-images.githubusercontent.com/1629196/75120209-0524e100-568a-11ea-9604-251c520a2d45.png)

2020-09-04 17:06 UTC, zneix commented
Fixing this would close #869

2020-09-05 08:32 UTC, alazymeme commented
Hello any news on this pr? I'm patiently waiting to use the pinching hand emoji in chatterino 🤏

2020-09-26 11:07 UTC, fourtf commented
Is this still being worked on or can I close?

2020-09-26 13:10 UTC, pajlada commented
Leave this up

2020-10-18 11:28 UTC, alazymeme commented
Looking forward to using the new emojis in chatterino 😁

2021-01-01 04:53 UTC, alazymeme commented
New year, new emojis 😄 can't wait for this to be implemented!

2021-01-18 10:56 UTC, alazymeme commented
Can't wait to prove these nerds wrong when I can see the window emoji 😲

2021-02-11 08:07 UTC, Mm2PL commented
Can't wait for this to be merged

2021-02-12 14:29 UTC, zneix requested changes
Looks good to me, new emojis work fine. Worth noting there's a very slow emoji load at the first launch, but since it seems to be cached and loads quicker later I guess it's fine :+1:

2021-02-12 14:29 UTC, zneix commented on src/providers/emoji/Emojis.cpp
> +
We should not use `printf` here

2021-02-12 16:08 UTC, pajlada commented
> Looks good to me, new emojis work fine. Worth noting there's a very slow emoji load at the first launch, but since it seems to be cached and loads quicker later I guess it's fine +1

Thanks for the review!
The slow speed is at least just as slow as it's been before, not slower, as it's hosted on the same provider & server and the filesizes are very similar for these set of emojis.

Still interested in finding a "true CDN" that isn't slow af, but the b2+cloudflare combo was megaslow

2021-02-12 23:19 UTC, alazymeme commented
We stopped using JoyPixels didn't we? Was looking at a basic CDN like this: https://cdnjs.com/libraries/emoji-toolkit

2021-02-13 08:42 UTC, pajlada commented
> We stopped using JoyPixels didn't we? Was looking at a basic CDN like this: https://cdnjs.com/libraries/emoji-toolkit

We did, yes

2021-02-13 16:26 UTC, pajlada commented
Waiting for #2453 to be merged in before running final tests on this and merging it

2021-02-13 18:17 UTC, merged