Add i.fourtf.com as an image uploader example
Chatterino/chatterino2 pull request #1880
Opened 2020-08-20 11:41 UTC by alazymeme

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

Adds fourtf's image uploader as an example for users that want to host their own 🚀

2020-08-20 15:05 UTC, zneix requested changes

2020-08-20 15:05 UTC, zneix commented on docs/IMAGEUPLOADER.md
> +
I think you could add some kind of information explaining that this is an example config for websites/servers hosting this project, not an actual uploading service.

2020-08-20 15:05 UTC, zneix commented on docs/IMAGEUPLOADER.md
> +|Extra headers|`Authorization: Basic <Your base64 encoded user and password>`|
Replace `<Your base64 encoder user and password>` with something way shorter, like `XXXXXXXXXXXXXXX` (from an example above) with information to replace that with authentication.

2020-09-20 13:52 UTC, alazymeme commented
Need to change this align with https://github.com/Chatterino/wiki/pull/6

2020-09-26 10:48 UTC, fourtf commented
doesn't make sense in this repo, if you add it to the wiki repo then I'll merge

2020-09-26 10:48 UTC, closed without merging

2020-09-26 11:20 UTC, alazymeme commented
https://github.com/Chatterino/wiki/pull/8