Fixed zooming bug in native-host-ext [Chrome]
Chatterino/chatterino2 pull request #1936
Opened 2020-09-02 23:25 UTC by mfmarlow

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description
Fixed a bug that misplaced the attached window when zooming on Chrome. Now gets pixel ratio data from the extension to determine the proper x location of chat. Still supports extension versions 1.2 and 1.3. 

Requires:

2020-09-04 14:37 UTC, alazymeme requested changes
Your PR introduces a new issue to where the chatterino extension will load with the page and not minimize at all despite there being no chat there.

![image](https://user-images.githubusercontent.com/12804673/92251324-045de900-ef10-11ea-842c-8cf71f711036.png)

2020-09-04 14:37 UTC, alazymeme commented on CHANGELOG.md
>  - Bugfix: /usercard command will now respect the "Automatically close user popup" setting (#1918)
```suggestion
- Minor: Disable checking for updates on unsupported platforms (#1874)
- Bugfix: Fixed bug misplacing chat when zooming on Chrome with Chatterino Native Host extension (#1936)
- Bugfix: Fix bug preventing users from setting the highlight color of the second entry in the "User" highlights tab (#1898)
- Bugfix: /usercard command will now respect the "Automatically close user popup" setting (#1918)
```

2020-09-24 10:10 UTC, 23rd commented on src/singletons/NativeMessaging.cpp
>          args.height = root.value("size").toObject().value("height").toInt(-1);
```suggestion

        {
            const auto sizeObject = root.value("size").toObject();
            args.x = sizeObject.value("x").toDouble(-1.0);
            args.pixelRatio = sizeObject.value("pixelRatio").toDouble(-1.0);
            args.width = sizeObject.value("width").toInt(-1);
            args.height = sizeObject.value("height").toInt(-1);
        }

```

2020-09-26 10:45 UTC, fourtf commented
Can someone verify that this works?

2020-09-29 09:08 UTC, alazymeme commented
> Can someone verify that this works? Also check with hi-dpi enabled in windows.

I can check, just need some form of a comment or change in regards to https://github.com/Chatterino/chatterino2/pull/1936#discussion_r494196666 and then I'll test it again

2021-07-10 09:46 UTC, jammehcow commented
Is this fix still needed or can it be closed?

2021-07-11 09:50 UTC, ALazyMeme approved these changes

2021-07-11 11:34 UTC, ALazyMeme commented
Confirmed the new chatterino build from this pr works just fine with the normal extension (without the zoom-related updated).

2021-07-25 11:34 UTC, ALazyMeme commented
@pajlada merge pls

2021-07-25 11:52 UTC, pajlada approved these changes

2021-07-25 12:50 UTC, pajlada approved these changes

2021-07-25 13:13 UTC, merged