add build status badges to README
Chatterino/chatterino2 pull request #1938
Opened 2020-09-03 13:29 UTC by swills

Just a "nice to have" thing, if you're interested.

2020-09-04 14:54 UTC, alazymeme commented
Is there a reason this can't be added along the top Chatterino heading? Why should there be another heading just for a build status?

2020-09-05 06:58 UTC, alazymeme requested changes

2020-09-05 06:58 UTC, alazymeme commented on README.md
> +
As aforementioned, these badges shouldn't have their own header. My suggestion would be to have them inline with the Chatterino 2 header. [Example](https://github.com/pajbot/pajbot)

2020-09-05 23:18 UTC, alazymeme approved these changes
![image](https://user-images.githubusercontent.com/12804673/92314920-e2548b80-f021-11ea-9898-3e3619140be1.png)

2020-09-06 09:07 UTC, pajlada approved these changes
:+1:

2020-09-06 09:08 UTC, merged