Apa toast rework2
Chatterino/chatterino2 pull request #1985
Opened 2020-09-25 23:21 UTC by apa420

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description
Toasts with crossplatform support.

Fixes #1000
Fixes #1435

2021-01-13 11:37 UTC, zneix requested changes
Apart from some of my minor nitpicks, is there anything stopping this from getting merged? I'd love to see changes from this PR in the application :+1:

2021-01-13 11:37 UTC, zneix commented on CHANGELOG.md
> +- Major: Crossplatform toast notification support.
```suggestion
- Major: Added Cross-platform toast notification support. (#1985)
```

2021-01-13 11:37 UTC, zneix commented on src/singletons/Toasts.cpp
> +    QString bottomText = "";
```suggestion
    QString bottomText;
```

2021-01-13 11:37 UTC, zneix commented on src/singletons/Toasts.cpp
> +                        QString("<b>" + channelName + "</b> just went live!"),
This just looks cleaner
```suggestion
                        QString("<b>%1</b> just went live!").arg(channelName),
```

2021-01-13 11:37 UTC, zneix commented on src/singletons/Toasts.cpp
> +                        QString("<b>" + channelName + "</b> just went live!"),
```suggestion
                        QString("<b>%1</b> just went live!").arg(channelName),
```

2021-07-10 09:52 UTC, jammehcow commented
@apa420 what benefit does creating a new notification framework have over fixing how chatterino natively sends notifications?

Maybe I'm missing something.

2021-07-10 10:58 UTC, Mm2PL commented
Currently notifications work ONLY on ~~winblows~~ windows

2021-07-10 14:00 UTC, apa420 commented
Primarily getting the notifications working cross-platform (not only windows version 8 or higher) and removing the wintoast dependancy

2021-07-10 14:08 UTC, apa420 commented
I'm open to closing this pr if someone gets an easy way of compiling snorenotify on windows. I had so much trouble with it I gave up on it.

2021-07-11 04:50 UTC, jammehcow commented
Looks like `snorenotify` has been replaced with [KNotifications](https://api.kde.org/frameworks-api/frameworks-apidocs/frameworks/knotifications/html/index.html). Might be better to pick that up?

2021-08-24 12:28 UTC, zneix commented
Related: #2044

I can have a second look at the PR later, update the branch and test it on Linux.

2024-03-16 11:43 UTC, pajlada commented
Going ahead and closing this PR, feel free to open a new one or re-open this one if this is something that you're still interested to work on

2024-03-16 11:43 UTC, closed without merging