updated readme to have the chocolatey link
Chatterino/chatterino2 pull request #2012
Opened 2020-09-30 21:37 UTC by cinemassacres

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description
when they accept it this should be merged

2020-10-01 08:42 UTC, alazymeme commented
@fourtf do you want the commands put directly onto the repo? Or just link to the package page?

2020-10-01 08:43 UTC, alazymeme commented on README.md
> -
Irrelevant change

2020-10-01 09:53 UTC, alazymeme commented on README.md
> +## chocolatey
```suggestion

## Chocolatey 
```

2020-10-01 11:31 UTC, TranRed commented
why does this have 11 commits for 2 lines of text, tho ?

![FarmingCommits](https://cdn.betterttv.net/emote/5ed57f8bfdee545e3065efcb/3x)

2020-10-01 22:11 UTC, cinemassacres commented
Closes #1981

2020-10-01 22:26 UTC, apa420 commented
Fix your commit tree...

2020-10-02 05:26 UTC, alazymeme commented
Unsure as to why my comments were marked as resolved when they evidently are not 🤔

2020-10-02 05:28 UTC, alazymeme requested changes

2020-10-02 05:28 UTC, alazymeme commented on README.md
> +## chocolatey
```suggestion

## Chocolatey
```

2020-10-02 05:28 UTC, alazymeme commented on README.md
> -
Irrelevant change, please revert this commit

2020-10-02 05:29 UTC, alazymeme commented on README.md
> +## chocolatey
Please keep the formatting consistent.

2020-10-03 13:41 UTC, RAnders00 requested changes

2020-10-03 13:41 UTC, RAnders00 commented on README.md
> + A chocolatey version is available [here](https://chocolatey.org/packages/chatterino).
The chocolatey section should be next to the Download section, not at the bottom next to things it isn't related to.

2020-10-03 13:46 UTC, RAnders00 commented
Sorry, I don't mean to be rude, but this change so incredibly minute that it's more work for us to suggest changes to you than it is worth it. For simplicity's sake, I will close this, and we will introduce a chocolatey link in the readme via #2017.

2020-10-03 13:46 UTC, closed without merging