Initial work
Chatterino/chatterino2 pull request #2019
Opened 2020-10-01 22:25 UTC by apa420

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

Fixes #964

2020-10-02 14:06 UTC, leon-richardt requested changes

2020-10-02 14:06 UTC, leon-richardt commented on src/widgets/settingspages/GeneralPage.hpp
> +                        getSettings()->lastMessageColor = selected.name();
`QColor::name()` does not respect alpha value of the color. Is that intended?

Alternatively, `QColor::name(QColor::HexArgb)` can be used to also save the alpha value.

2020-10-02 14:06 UTC, leon-richardt commented on src/widgets/settingspages/GeneralPage.hpp
> +            colorButton, &ColorButton::clicked, [setting, colorButton]() {
nit: `ColorButton::color()` could be used to obtain the color instead of also passing `setting` to the lambda

2020-10-03 11:50 UTC, pajlada commented
I sent a PR to your branch in your repo :eyes: once that's merged in I'm happy to merge this

2020-10-03 12:27 UTC, zneix commented on src/widgets/settingspages/GeneralPage.cpp
> +        "can be loaded for all links if enabled.  Optionally you can also show "
Small nit: looks like you've got an extra space here.

2020-10-04 12:43 UTC, pajlada approved these changes
:+1: Looks good to me - thanks for the contribution!

2020-10-04 16:26 UTC, merged