Search with google feature
Chatterino/chatterino2 pull request #2067
Opened 2020-10-12 05:51 UTC by Y0dax

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

Added a basic search with google feature for selected text in channel messages. (#2058)

There is ongoing discussion regarding allowing different search engines, but I figured it would be good to get the basic feature out there which can be enhanced later.

2020-10-12 06:31 UTC, leon-richardt requested changes
Important note: Should probably wait for @fourtf or @pajlada to express their opinion on #2058 before investing too much time into implementation.

2020-10-12 06:31 UTC, leon-richardt commented on CHANGELOG.md
> +- Minor: Added search with google feature (#2058)
Please place "Minor" entries in the changelog below the "Major" entries.

2020-10-12 06:31 UTC, leon-richardt commented on src/widgets/helper/ChannelView.cpp
> +                QUrl("https://google.com/search?q=" + query));
I do not like this string being hardcoded here. Consider extracting the opening of the link into an own class, especially in regards to custom search query schemas potentially being added later on.

2020-10-13 05:31 UTC, closed without merging

2020-10-13 05:33 UTC, Y0dax commented
Closing while discussion is ongoing.