Update HighlightingPage.cpp
Chatterino/chatterino2 pull request #2404
Opened 2021-01-24 18:48 UTC by AweesneW

Applies changes mentioned in issue #2403

2021-01-24 19:40 UTC, leon-richardt commented on src/widgets/settingspages/HighlightingPage.cpp
> +                view->getTableView()->horizontalHeader()->hideSection(5);
```suggestion
                view->getTableView()->horizontalHeader()->hideSection(
                    HighlightModel::Column::UseRegex);
                view->getTableView()->horizontalHeader()->hideSection(
                    HighlightModel::Column::CaseSensitive);
```

Your change gets rid of the "Case-sensitive" column but the "Enable regex" column is then shown instead (se image)
.

2021-01-24 19:43 UTC, leon-richardt requested changes

2021-01-24 19:43 UTC, leon-richardt commented on src/widgets/settingspages/HighlightingPage.cpp
Your change gets rid of the "Case-sensitive" column but the "Enable regex" column is then shown instead (see image).

![image](https://user-images.githubusercontent.com/35232120/105641497-8a110f80-5e84-11eb-8172-a1995b7a1056.png)

```suggestion
                view->getTableView()->horizontalHeader()->hideSection(
                    HighlightModel::Column::UseRegex);
                view->getTableView()->horizontalHeader()->hideSection(
                    HighlightModel::Column::CaseSensitive);
```
This suggestion hides both columns and also uses the existing `Column` enum which is more readable. :smile:

2021-01-31 23:26 UTC, pajlada requested changes
Please add a changelog entry for this change - you can get hints for phrasing in #2403

2021-02-12 12:50 UTC, pajlada approved these changes

2021-02-12 13:43 UTC, merged