Updated building docs regarding CMake update
Chatterino/chatterino2 pull request #2585
Opened 2021-04-01 14:10 UTC by zneix

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable
no changelog entry needed

# Description

- Updated required packages on Arch GNU/Linux ![It's me Leon, not mm pepeLaugh](https://cdn.betterttv.net/emote/5fd0d7898c4e2c46195d6e27/1x)
- Updated required packages on Ubuntu

2021-04-02 14:12 UTC, pajlada commented on BUILDING_ON_LINUX.md
> +### Using QMake
Let's indent it further :)
```suggestion
#### Using QMake
```

2021-04-02 14:12 UTC, pajlada commented on BUILDING_ON_LINUX.md
> +### Using CMake
Let's indent it further :)
```suggestion
#### Using CMake
```

2021-04-02 14:13 UTC, pajlada requested changes
two smol changes, please commit those in if they seem good and we can get this merged in :)

2021-04-02 15:03 UTC, zneix commented
I Resolved the indentation issues :+1: Also added a note about `pulseaudio-qt` package being an optional dependency for Arch GNU/Linux - it's required (on pulseaudio systems) for chatterino to output audio on events like highlights and live notifications

2021-04-04 13:57 UTC, pajlada commented on BUILDING_ON_LINUX.md
> +
Let's leave this for a future PR since it requires a bit more testing

```suggestion
```

2021-04-04 13:57 UTC, pajlada approved these changes
LGTM :+1:

2021-04-04 13:58 UTC, merged