Keyboard integration for streamlink quality selection
Chatterino/chatterino2 pull request #2643
Opened 2021-04-18 17:59 UTC by M4tthewDE

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

This pr allows the confirmation of the streamlink quality selection by hitting Enter. 
The selection can be cancelled by pressing Escape. 

Not experienced with qt, so feedback appreciated :)

2021-04-18 18:02 UTC, Mm2PL requested changes

2021-04-18 18:02 UTC, Mm2PL commented on src/widgets/dialogs/QualityPopup.cpp
> +}
Use `createWindowShortcut` instead

2021-04-19 12:30 UTC, zneix commented
I think this is such a small thing that it doesn't necessarily require a changelog entry.

2021-08-14 11:04 UTC, zneix commented
I think instead of adding a shortcut for Enter, rather changing the default button or something along these lines should be done instead. That'd be consistent with all other button behavior's among the codebase and cleaner in my opinion. I'll to fiddle around this one for a little bit now.
Just making a comment before pajlada gets to see this PR.

2021-08-15 14:00 UTC, pajlada commented
Fixed in #3169

2021-08-15 14:00 UTC, closed without merging