Added placeholder to tab rename dialog's input
Chatterino/chatterino2 pull request #2713
Opened 2021-04-28 08:58 UTC by zneix

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

Adds simple placeholder which shows either custom tab title (if set) or default tab name.

![Farming commits](https://cdn.zneix.eu/quEX9PH.png)

Closes #2709

2021-04-28 09:19 UTC, jammehcow commented
Tested, LGTM 👍

2021-04-28 09:19 UTC, jammehcow approved these changes

2021-04-28 22:05 UTC, fourtf commented
Even though this is the suggested solution from issue thread I'm not sure if this solves the issue accurately. A placeholder should help the user understand what he has to input and I don't think that showing up he channel name does that.

2021-05-01 12:53 UTC, fourtf commented
I played around a bit in figma and came up with this:
![image](https://user-images.githubusercontent.com/6320036/116782935-3ff38780-aa8c-11eb-9d9e-1699c4478cfd.png)

It incorporates some other elements to make it more clear what the dialog is for and what the user has to input. I looked at the right click menu of the tab and tried to improve on it a bit to also make it more clear there.

#2709

2021-05-01 16:55 UTC, zneix commented
What I managed to achieve:

![layouts are dank](https://cdn.zneix.eu/jQwB68f.png) ![my transparency is even danker](https://cdn.zneix.eu/GfByZ4W.png)

2021-05-01 21:38 UTC, Mm2PL requested changes

2021-05-01 21:38 UTC, Mm2PL commented on src/widgets/helper/NotebookTab.cpp
> +    auto cancelButton = new QPushButton("Canel");
canel forsenT

2021-05-02 09:42 UTC, pajlada commented on src/widgets/helper/NotebookTab.cpp
> +    auto buttonBox = new QHBoxLayout;
Use a https://doc.qt.io/qt-5/qdialogbuttonbox.html instead

2021-05-02 10:57 UTC, pajlada approved these changes
LGTM :+1: Merge in after adding the changelog entry as agreed

2021-05-02 10:59 UTC, merged