Fix newlines in stream title causing text in header to go out of bounds
Chatterino/chatterino2 pull request #2755
Opened 2021-05-08 08:03 UTC by jupjohn

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

When a stream title has newlines at the end of the text it causes the text in the split header to move upwards. This change just removes the newlines from the end of the string (including whitespace) to prevent this from happening.

### Before:

![Chatterino2_Jammehcow_NewlineTitlePre](https://user-images.githubusercontent.com/4962764/117531767-5b383700-b038-11eb-9dce-c9ad198ccfeb.png)

### After:

![Chatterino2_Jammehcow_NewlineTitlePost](https://user-images.githubusercontent.com/4962764/117531768-5c696400-b038-11eb-949d-2b4995a9926d.png)

2021-05-08 12:14 UTC, jammehcow commented
could almost just replace any newline. would like to test with newlines in the middle of title

2021-05-08 13:00 UTC, apa420 commented
You can have newlines anywhere in the title so we need to regex all newlines and replace them as spaces like twitch does. Then probably have to run the qtstring function which removes double spaces or w/e.

2021-05-08 14:05 UTC, pajlada requested changes
Small change to support titles like:
```
foo
bar
baz
```

which on Twitch shows up as `foo bar baz`

2021-05-08 14:05 UTC, pajlada commented on src/widgets/splits/SplitHeader.cpp
> +
The 'phantom newlines' can be added through the Twitch website when changing your title by simply pressing enter in the title box.

On the Twitch website, all newlines in the title are stripped.

There's a handy dandy QString function in Qt5 for solving this called `simplified` (see https://doc.qt.io/qt-5/qstring.html#simplified)

```suggestion
        if (settings.headerStreamTitle && !s.title.isEmpty())
        {
            title += " - " + s.title.simplified();
        }

```

2021-05-09 09:02 UTC, pajlada approved these changes

2021-05-09 09:22 UTC, merged