remove weird logic with temp variable
Chatterino/chatterino2 pull request #2800
Opened 2021-05-20 14:46 UTC by fourtf

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

removes some weird 20 lines of code that are actually two lines of normal code

2021-05-22 12:58 UTC, pajlada commented
I'm still having hard times wrapping my head around the if. I'm not sure if it's double negation + && or if it's the nested conditional - my counter-proposal would be to wrap the logic in a private function, something akin to this:
```cpp
bool TwitchMessageBuilder::shouldAddModerationElements() const {
    if (this->senderIsBroadcaster) {
        return false;
    }

    if (this->tags.value("user-type").toString() == "mod" && this->args.isStaffOrBroadcaster) {
        return false;
    }

    return true;
}
```

We wouldn't shave off any lines, but the logic for moderation buttons is clear, concise enough (7 lines of code vs the previous 20-line mess)

This is not a hill I'm willing to die on, so if that's unacceptable I'd be fine with a comment above the code instead

2021-05-23 10:10 UTC, apa420 commented on src/providers/twitch/TwitchMessageBuilder.cpp
> +        !(this->tags.value("user-type") == "mod" && !args.isStaffOrBroadcaster))
```suggestion
    if (!(this->senderIsBroadcaster ||
        (this->tags.value("user-type") == "mod" && !args.isStaffOrBroadcaster)))
```

Would this fix the confusion @pajlada ?

2021-05-23 12:45 UTC, pajlada commented on src/providers/twitch/TwitchMessageBuilder.cpp
> +        !(this->tags.value("user-type") == "mod" && !args.isStaffOrBroadcaster))
No

2021-05-23 14:46 UTC, pajlada requested changes
I'm still having hard times wrapping my head around the if. I'm not sure if it's double negation + && or if it's the nested conditional - my counter-proposal would be to wrap the logic in a private function, something akin to this:
```cpp
bool TwitchMessageBuilder::shouldAddModerationElements() const {
    if (this->senderIsBroadcaster) {
        return false;
    }

    if (this->tags.value("user-type").toString() == "mod" && this->args.isStaffOrBroadcaster) {
        return false;
    }

    return true;
}
```

We wouldn't shave off any lines, but the logic for moderation buttons is clear, concise enough (7 lines of code vs the previous 20-line mess)

This is not a hill I'm willing to die on, so if that's unacceptable I'd be fine with a comment above the code instead

2021-08-14 11:03 UTC, pajlada approved these changes

2021-08-14 11:06 UTC, merged