Fix write connection reconnection issues
Chatterino/chatterino2 pull request #2850
Opened 2021-06-01 12:56 UTC by Bun

Ready for review/feedback. There's a lot of room for (additional) refactoring on the connection logic, but I figured I'd at least fix the issue first.

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

Chatterino currently does not handle disconnects of the write connection, which
causes messages to remain buffered until you manually reconnect, after which it
will send all messages at once.

This patch addresses the lack of reconnection specifically, and attempts to
refactor some of the reconnection logic to make it more robust. Backoff behavior
is introduced to *both* read/write cons to avoid reconnection loops.

To replicate the issue, simply lose your (write) connection to TMI. This can be
"simulated" using something like:

    tcpkill -i eth0 host 44.226.36.141 or host 34.217.198.238 or host 100.20.159.232

An alternative/secondary approach would be to detect failures of the underlying
`sendRaw` method (as it returns false if the message can't be sent to the
connection), but better monitoring of the connection state should be sufficient.

The way the code is setup currently doesn't really make it easy to implement
this "cleanly". E.g. calls `initializeConnection` are skipped on reconnect, but
since we're reconnecting with the same parameters, this should have little
actual consequence.

2021-06-01 17:46 UTC, fourtf commented
big if true

2021-06-01 21:10 UTC, Mm2PL commented
huge if factual

2021-06-01 21:23 UTC, leon-richardt commented
enormous if accurate

2021-06-02 09:04 UTC, alazymeme commented
sizeable if veracious

2021-06-02 11:51 UTC, Bun commented
Account switching (including updating your own OAuth token) doesn't work properly, because the disconnect triggered by `AbstractIrcServer::connect` causes it to autoreconnect with the current credentials before `initializeConnection` is called. It does reconnect eventually (after 15s), but that's not how it should work.

Working on a fix.

2021-06-02 14:11 UTC, Felanbird commented on CHANGELOG.md
> +- Bugfix: Fix reconnecting when IRC write connection is lost
```suggestion
- Bugfix: Fix reconnecting when IRC write connection is lost (#1831, #2356, #2850)
```
adding issue #1831, #2356 and this pr to the changelog

2021-06-02 14:13 UTC, Felanbird commented on CHANGELOG.md
> +- Bugfix: Fix reconnecting when IRC write connection is lost
also referencing #2692, even though you stated you were working on the reconnection aspect

2021-06-02 19:37 UTC, Bun commented
The behavior should be OK now. (Also shouldn't have force pushed a formatting mistake, oops.)

2021-06-06 12:15 UTC, pajlada commented on src/providers/irc/IrcConnection2.cpp
> +                this->expectConnectionLoss_ = true;
This seems like a noop since we already set `this->expectConnectionLoss_ = true;` in the `IrcConnection::close()` method

2021-06-06 12:19 UTC, pajlada commented on src/providers/irc/IrcConnection2.cpp
> +                    // Ensure we always notify our parent that we should
Could you expand on the comments here explaining under what circumstances we wouldn't want to call connectionLost here?

2021-06-06 12:22 UTC, pajlada requested changes
Looks good to me - I'm fine to merge this in pending some comments being added

Thanks a lot for looking into this!

2021-06-06 12:48 UTC, Bun commented
Shuffled some state resets around and improved the comments. Let me know if that's sufficient.

2021-06-06 13:14 UTC, pajlada commented
> Shuffled some state resets around and improved the comments. Let me know if that's sufficient.

Perfect, thank you.

I'll merge this into master and have people take this for a spin in the nightly version!

2021-06-06 13:14 UTC, pajlada approved these changes

2021-06-06 14:25 UTC, merged