Use an exponential backoff when deciding how long we need to wait for timeouts
Chatterino/chatterino2 pull request #2892
Opened 2021-06-13 13:55 UTC by pajlada

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

Instead of always waiting ~15 seconds for a reconnect, we now follow the guidelines from https://dev.twitch.tv/docs/irc/guide#re-connecting-to-twitch-irc and increase our reconnect delays exponentially.
Our reconnect delay starts at 1 second and caps out at 16 seconds.

2021-06-13 19:48 UTC, leon-richardt requested changes

2021-06-13 19:48 UTC, leon-richardt commented on src/providers/irc/IrcConnection2.cpp
>      // Accurately track the time a connection was opened
This comment is also no longer needed

```suggestion
```

2021-06-17 19:13 UTC, leon-richardt approved these changes

2021-06-20 11:44 UTC, zneix approved these changes

2021-06-20 11:47 UTC, Mm2PL approved these changes

2021-06-20 13:29 UTC, merged