xHeaveny/add/wiki/about
Chatterino/chatterino2 pull request #3068
Opened 2021-07-24 10:37 UTC by xHeaveny

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

Added "About Chatterino" to the About tab
Cleared issue #2965 with this

2021-07-24 10:51 UTC, pajlada commented on src/widgets/settingspages/AboutPage.cpp
> +            l.emplace<QLabel>("Join the official Chatterino <a href=\"https:/\discord.gg/7Y5AYhAK4z\">Discord</a>")->setOpenExternalLinks(true);
The discord link is broken
```suggestion
            l.emplace<QLabel>("Join the official Chatterino <a href=\"https://discord.gg/7Y5AYhAK4z\">Discord</a>")->setOpenExternalLinks(true);
```

2021-07-24 10:52 UTC, pajlada commented on src/widgets/settingspages/AboutPage.cpp
> +        auto about_chatterino = layout.emplace<QGroupBox>("About Chatterino...");
rename this variable to be camelCase, so `aboutChatterino`

2021-07-24 10:54 UTC, pajlada requested changes
Would be nice to have the links defined at the top of this file as constexpr strings or something along those lines to make future changes easier

2021-07-24 21:17 UTC, pajlada requested changes
Would still like the links in a constexpr or define at the top of the file, and the formatting seems to fail so please check your `clang-format`

2021-07-24 21:17 UTC, pajlada commented on CHANGELOG.md
> +- Minor: Added "About Chatterino" to About tab. (#2965, #3066)
Could you add a small description of what's in the About Chatterino section? e.g. that it links to the wiki

2021-07-25 10:35 UTC, pajlada commented
Another request: Please put the "About Chatterino" section above "Open source software used"

2021-07-25 13:38 UTC, pajlada requested changes
Final changes (I think)

2021-07-25 13:38 UTC, pajlada commented on src/widgets/settingspages/AboutPage.cpp
> +#define chatterinoDiscord "https://discord.gg/7Y5AYhAK4z/"
```suggestion
#define LINK_CHATTERINO_WIKI "https://wiki.chatterino.com"
#define LINK_DONATE "https://streamelements.com/fourtf/tip"
#define LINK_CHATTERINO_FEATURES "https://chatterino.com/#features"
#define LINK_CHATTERINO_DISCORD "https://discord.gg/7Y5AYhAK4z"
```

2021-07-25 13:38 UTC, pajlada commented on src/widgets/settingspages/AboutPage.cpp
> +            l.emplace<QLabel>("Join the official Chatterino <a href=\""chatterinoDiscord "\">Discord</a>")->setOpenExternalLinks(true);
```suggestion
            l.emplace<QLabel>("Chatterino Wiki can be found <a href=\""LINK_CHATTERINO_WIKI"\">here</a>")->setOpenExternalLinks(true);
            l.emplace<QLabel>("Support <a href=\""LINK_DONATE"\">Chatterino</a>")->setOpenExternalLinks(true);
            l.emplace<QLabel>("All about Chatterino's <a href=\""LINK_CHATTERINO_FEATURES"\">features</a>")->setOpenExternalLinks(true);
            l.emplace<QLabel>("Join the official Chatterino <a href=\""LINK_CHATTERINO_DISCORD "\">Discord</a>")->setOpenExternalLinks(true);
```

2021-07-25 13:39 UTC, pajlada commented on src/widgets/settingspages/AboutPage.cpp
> +            l.emplace<QLabel>("Join the official Chatterino <a href=\"" chatterinoDiscord "\">Discord</a>")->setOpenExternalLinks(true);
```suggestion
            l.emplace<QLabel>("Chatterino Wiki can be found <a href=\"" LINK_CHATTERINO_WIKI "\">here</a>")->setOpenExternalLinks(true);
            l.emplace<QLabel>("Support <a href=\"" LINK_DONATE "\">Chatterino</a>")->setOpenExternalLinks(true);
            l.emplace<QLabel>("All about Chatterino's <a href=\"" LINK_CHATTERINO_FEATURES "\">features</a>")->setOpenExternalLinks(true);
            l.emplace<QLabel>("Join the official Chatterino <a href=\"" LINK_CHATTERINO_DISCORD "\">Discord</a>")->setOpenExternalLinks(true);
```

2021-07-25 13:42 UTC, pajlada approved these changes

2021-07-25 13:47 UTC, pajlada commented on CHANGELOG.md
> +- Minor: Added "About Chatterino" to About tab where The Chatterino Wiki and other Stuff can be found. (#2965, #3068)
```suggestion
- Minor: Added section with helpful Chatterino-related links to the About page. (#3068)
```

2021-07-25 13:51 UTC, zneix approved these changes

2021-07-25 14:19 UTC, merged