Adding xHeaveny to Contributor List
Chatterino/chatterino2 pull request #3072
Opened 2021-07-25 17:04 UTC by xHeaveny

Pull request checklist:

- [x] `CHANGELOG.md` ~was updated, if applicable~

2021-07-25 19:49 UTC, zneix requested changes
Please read the instructions regarding added avatar and update it.

> Avatar should be located in avatars/ directory. Its size should be 128x128
> Make sure to reduce avatar's size as much as possible with tool like pngcrush or optipng and run ./generate_resources.py

2021-07-26 06:41 UTC, xHeaveny commented
> Please read the instructions regarding added avatar and update it.
> 
> > Avatar should be located in avatars/ directory. Its size should be 128x128
> > Make sure to reduce avatar's size as much as possible with tool like pngcrush or optipng and run ./generate_resources.py

done 👍

2021-07-31 11:04 UTC, pajlada approved these changes

2021-07-31 11:05 UTC, zneix approved these changes

2021-07-31 12:47 UTC, merged