Deprecated /(un)follow commands and respective usercard action
Chatterino/chatterino2 pull request #3078
Opened 2021-07-27 22:49 UTC by zneix

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

As announced, `/helix/users/follows` endpoints have been decomissioned today.

![farewell, beautiful Helix code](https://cdn.zneix.eu/ffv9LsN.png)

2021-07-27 23:09 UTC, zneix commented
For now, `/follow` and `/unfollow` have been marked as deprecated:
![saj](https://cdn.zneix.eu/XcYWeda.png)

And for the time being, follow checkbox in usercard remains but it's permanently disabled:
![CoolCat](https://cdn.zneix.eu/59oWZeT.png)

This maybe isn't the ideal solution as it could confuse users, making them think they can still (un)follow and try to click the checkbox.
We could either:
1. Remove the checkbox and checking if current user follows the user of whom usercard is opened altogether.
2. Think of some alternative, like the one that @mm2pl suggested:

<details>
<summary>Click to expand</summary>

![GIMP masters](https://i.imgur.com/V7s8g2y.png)

</details>

2021-07-28 01:48 UTC, Felanbird requested changes
`Minor English loophole:`
Twitch has taken away our ability to manage follows, not the quality of, or possibility to make changes for the endpoint. 
https://wikidiff.com/ability/possibility

As for the changelog I'm indifferent in the usage of (un)follow 🤷

2021-07-28 01:48 UTC, Felanbird commented on src/controllers/commands/CommandController.cpp
> +            "Twitch has removed possibility to follow users through "
```suggestion
            "Twitch has removed the ability to follow users through "
```

2021-07-28 01:48 UTC, Felanbird commented on src/controllers/commands/CommandController.cpp
> +            "Twitch has removed possibility to unfollow users through "
```suggestion
            "Twitch has removed the ability to unfollow users through "
```

2021-07-28 01:48 UTC, Felanbird commented on CHANGELOG.md
> +- Major: Deprecated `/(un)follow` commands and (un)following in the usercards as Twitch removed the possibility to (un)follow users.
```suggestion
- Major: Deprecated `/(un)follow` commands and (un)following in the usercards as Twitch has removed this feature for 3rd party applications. (#3076, #3078)
```

2021-07-28 02:33 UTC, Felanbird commented
As for the future of the button, I'm going to put my vote for keeping the button with its ability show follow status as currently handled, but making the functionality return an error message, as done with the slash commands in this PR.

Possibly removing it in the future if we need button room for some reason.

<!----
1. Keep the button and make the functionality return error information. (as done with the slash commands)
2. Remove the functionality and change the button to `Following` as to indicate the following status.
3. **Both** - Button with error message - visual functionality still exists - worded as `Following`.
4. Remove it all together now. 
---->

2021-07-29 00:24 UTC, zneix commented
> but making the functionality return an error message, as done with the slash commands in this PR.

As I've stated in my comment under this PR:

> follow checkbox in usercard remains but it's permanently disabled

Do you mean we should keep the functionality of the button but add error messages notifying users that (un)following failed or did you just overlook that part where I said it? I believe there should be no logic for event actions related to that button as it's gonna be literally cosmetic at this point (if we decide to keep it in the first place that is).

2021-07-29 02:08 UTC, Felanbird commented
> Do you mean we should keep the functionality of the button but add error messages notifying users that (un)following failed 

Yes, I think if we keep the button it should at least do something indicating to users that the attempt failed.
![](https://i.imgur.com/FG4GxkE.gif)



> I believe there should be no logic for event actions related to that button as it's gonna be literally cosmetic at this point  (if we decide to keep it in the first place that is).

If we to remove the all logic we should just remove the button in its entirety, no need for a cosmetic button.

2021-07-31 10:49 UTC, pajlada approved these changes

2021-07-31 11:27 UTC, Felanbird commented
Works as intended, the only problem seems to be the loading time, you have hover the button for 1.5~ seconds before the prompt appears. It took me a while to actually get the prompt because I was clicking the "button" and and doing so resets the loading.

![image](https://user-images.githubusercontent.com/41973452/127738304-0bdd7936-285f-43d0-922d-842a05591ef8.png)

2021-08-01 10:32 UTC, pajlada commented
> Works as intended, the only problem seems to be the loading time, you have hover the button for 1.5~ seconds before the prompt appears. It took me a while to actually get the prompt because I was clicking the "button" and and doing so resets the loading.
> 
> ![image](https://user-images.githubusercontent.com/41973452/127738304-0bdd7936-285f-43d0-922d-842a05591ef8.png)

That's unfortunately fairly tricky for us to solve without creating a new QCheckBox type and re-implementing it's click handler making it show the tooltip.

2021-08-01 11:08 UTC, Mm2PL commented
About the usercard: maybe we could change the text color/effects. For example gray out the `Follow` text or cross it out.

2021-08-01 11:39 UTC, pajlada commented
All in favour of removing the checkbox?

2021-08-01 22:37 UTC, Felanbird approved these changes

2021-08-01 23:45 UTC, pajlada approved these changes

2021-08-04 20:03 UTC, Mm2PL approved these changes
lgtm

2021-08-04 20:41 UTC, merged