Regex nicknames
Chatterino/chatterino2 pull request #3146
Opened 2021-08-07 21:28 UTC by apa420

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description
Added regex option to nicknames, might be scuffed from my testing it worked, it does though take the whole username and not just the part matched.

2021-08-08 10:29 UTC, Mm2PL requested changes
I'm unable to get references to the original username working. That works in ignores and maybe should work here too.

2021-08-09 16:39 UTC, Mm2PL approved these changes

2021-08-09 18:28 UTC, xHeaveny approved these changes

2021-08-22 02:21 UTC, Felanbird commented
I'm unsure if this is something we can fix, but if you leave the username box blank with regex enabled, it places the nicknamed phrase in-between every character of the username.

![image](https://user-images.githubusercontent.com/41973452/130339747-7379e12a-d846-4292-81c8-c894b13c424c.png)

![image](https://user-images.githubusercontent.com/41973452/130339696-f21f0277-e386-47e8-9df8-4cca59a63a27.png)
Case-sensitivity setting having no effect on this fact.

2021-08-22 09:51 UTC, pajlada commented
Real use cases:
 - Anonymize chat by replacing `.+` with `User`. (New use case)
 - Simplifies doing modifications on usernames instead of full replacement, i.e. if I want to add a star to `zneix`'s and `gempir`'s names, I could add the following replacements: `zneix` -> `⭐ \1`, `gempir` -> `⭐ \1` instead of `zneix` -> `⭐ zneix` and `gempir` -> `⭐ gempir`. (Simplifies already possible use case)
 - Filter out offensive phrases from usernames. While most offensive phrases might be caught by Twitch already, some offensive phrases are more personal. (New use case)

Meme use cases:
 - Putting a badge in front of everyone's username by replacing `.+` with `🐝 \1`

2021-08-22 10:36 UTC, pajlada approved these changes

2021-08-22 11:29 UTC, zneix approved these changes

2021-08-22 11:30 UTC, merged