Ignore phrase by specified user
Chatterino/chatterino2 pull request #3153
Opened 2021-08-09 03:09 UTC by mammothb

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

- Added an additional "User" column to the Ignores -> Messages tab to allow users to set ignore patterns for a specific user
- Intended usecase: when a user is spamming too much of a particular emote and you would like to filter that out while still see the emote when you or other users send it

2021-08-09 10:22 UTC, apa420 commented
Can't the R9K mode in chatterino do this already? ( Blocking spam by the same user )

Should this only be able to add one user per field.
Which means that if you wanted to add this to ~10 people you'd have to create the same ignore pattern 10 times.
Supporting splitting users with `,` might be a good idea. `user1, user2, user3` or `user1 user2` etc.
Or support regex for the user field like #3146.

2021-08-09 10:54 UTC, mammothb commented
This is really just for the niche use case where you only want to replace the "annoying" part of a user's message without blocking the entire message or user. I initially developed this for personal use but someone in chat asked me to make a PR so here it is.

Based on that use case, I'm not sure if people will be applying the pattern to multiple users, at least that hasn't been the case for me. However, if you think that supporting splitting users might still be useful, I'll try to implement that.

2021-08-09 11:03 UTC, apa420 requested changes

2021-08-09 11:03 UTC, apa420 commented on src/widgets/settingspages/IgnoresPage.cpp
> +        {"Pattern", "User", "Regex", "Case Sensitive", "Block", "Replacement"});
Line 44 (that github doesn't let me mark)
You should add a comment says something like: "Leaving the User tab empty will make it target all users"

2021-08-09 23:15 UTC, apa420 commented on src/widgets/settingspages/IgnoresPage.cpp
> +        "Leaving the User tab empty will make it target all users");
```suggestion
        "Ignore messages based certain patterns.\n"
        "Leaving the User tab empty will make it target all users");
```

2021-08-09 23:19 UTC, apa420 commented on src/providers/twitch/TwitchMessageBuilder.cpp
> +        if (user.isEmpty() &&
Shouldn't this be 
```suggestion
        if (!user.isEmpty() &&
```
So it's the same as before?

2021-08-09 23:20 UTC, apa420 commented on src/providers/twitch/TwitchMessageBuilder.cpp
> +        if (user.isEmpty() &&
Also you can press commit suggestion here on github and it'll automatically do the work for you if you agree with the change.

2021-11-28 13:44 UTC, mammothb commented
Sorry that this too longer than intended, splitting users by `,` has been implemented. And I updated the placeholder entry to `user1,user2` to demonstrate that.

2023-11-05 10:37 UTC, pajlada commented
Closing this for now, feel free to reach out or create a discussion to discuss your use-case further.

2023-11-05 10:37 UTC, closed without merging