Track timeout/slowmode status
Chatterino/chatterino2 pull request #3329
Opened 2021-10-30 15:10 UTC by Bun

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

This PR adds a timer to the chat input box (on the left side of the message length counter) that reflects how long until you can chat again. It supports timeouts (on CLEARCHAT and on error notice) and slowmode (including the error notice), but doesn't query e.g. an existing timeout on application restart.

Some of the choices were made in good faith but may be a bit arbitrary, so please nitpick away and let me know if anything should be changed:
* The `color: gold` text for the timer label
* Minor refactor/cleanup of how notices are handled (nb: the PR makes sure to keep logic with side-effects in the `handle*` function instead of `parse*`, which does mean parsing the notice twice)
* Technically, if the timer is between 1s and 0s Twitch will still block you from sending, but at <1s the timer label goes away. Let me know if this is something that should be "fixed".

2021-11-02 18:52 UTC, Felanbird requested changes
Just a few grammar things, the functionality itself seems to work well.

`note:` I'm not crazy about the setting name but I don't have another suggestion right now.

2021-11-02 18:52 UTC, Felanbird commented on src/providers/twitch/TwitchChannel.cpp
> +                // have time remaining if the user was too eager to send a
```suggestion
                // have time remaining, if the user was too eager to send a
```
also thought about replacing if with because but 🤷

2021-11-02 19:18 UTC, Felanbird commented
![image](https://user-images.githubusercontent.com/41973452/139929761-0d56c7fa-4b31-4f24-b2ed-7c623d2a42ea.png)

I found the edge case, but it's probably not that important. 

When you attempt to send a message in a channel with verified chat restrictions (phone number in this example [#bobross]), the timer will start and refresh on each message, although the slowmode restriction is likely not applying.

I don't know if we should handle these messages or just ignore this "issue".

2021-11-03 10:04 UTC, Bun commented
>  Being a subscriber does not bypass the slow-mode timer, despite subs being immune to slow-mode.

Whether subs are affected is actually a setting for affiliate+ , in Dashboard -> Settings -> Affiliate: "Allow subscribers to chat freely in your channel when chat is in slow mode" and I believe it's disabled by default. Regardless, there doesn't seem to be a public way to query this. We could err on the safe side I guess and only show the countdown if you end up sending too fast.

> Messages that are sent in channels where you don't meet the verified chat restrictions (phone number etc.. - [#bobross as example]), trigger the timer despite the fact that no message was sent. (Can be handled as you receive back a message).

I considered showing the timer upon receiving USERSTATE instead of after sending the message, but thought it would add extra (UI) latency so decided against it. It does however feel more correct, especially considering things like that^.

> Messages that are sent in hyper-fast chats trigger the timer, despite the fact that no message was sent. (Probably not handle-able as you do not receive a message when these are dropped).

You tested that I assume? For example, for the Twitch-side duplicate message check it doesn't matter if your message was actually shown in chat or not, so I would assume it works like that for slowmode as well. (?)

2021-11-03 11:20 UTC, LosFarmosCTL commented
> I believe it's disabled by default.

Yes, it is 100% disabled by default.

2021-11-03 13:15 UTC, Felanbird commented
> it's disabled by default. 

I forgot about this fact.

> I considered showing the timer upon receiving USERSTATE instead of after sending the message, but thought it would add extra (UI) latency so decided against it. It does however feel more correct, especially considering things like that^.

I'm indifferent about this one anyway, we are probably better off letting people think said message attempt triggered slow-mode anyway.

> You tested that I assume? For example, for the Twitch-side duplicate message check it doesn't matter if your message was actually shown in chat or not, so I would assume it works like that for slowmode as well. (?)

You're likely to be correct about this one as well, I'll re-test later today when somebody else with a hyper-fast chat goes live.

2021-11-06 13:30 UTC, NS2555 commented
as the only light/white mode user of chatterino, please ensure the timer has enough contrast in chatterino light/white modes, because judging by the fact it uses a bright yellow color which is not a normal chatterino color, it is going to end up being almost completely invisible

2021-11-06 13:33 UTC, Felanbird commented
> 
> 
> as the only light/white mode user of chatterino, please ensure the timer has enough contrast in chatterino light/white modes, because judging by the fact it uses a bright yellow color which is not a normal chatterino color, it is going to end up being almost completely invisible

This is a good point
white
![image](https://user-images.githubusercontent.com/41973452/140611553-0aa32e16-41e7-4dad-8234-76453324d16e.png)
light
![image](https://user-images.githubusercontent.com/41973452/140611557-fc8e4f1c-d607-4780-bfae-df731ab6fe3b.png)

2021-11-06 13:39 UTC, NS2555 commented
i suggest using a different color hue all together, i tested some things here and there and found out `#00526D` works pretty well 
![image](https://user-images.githubusercontent.com/18615981/140611731-3422c797-24be-4cb9-96eb-a6096d33df74.png)

2021-11-06 14:06 UTC, pajlada commented
In general, functionality looks good. There's some further code review/refactoring that I'd like to see but will leave it for tomorrow or next week.
Will need a little bit more testing with edge-cases but they're pretty well documented here or in the code already which is nice.

2024-03-17 11:26 UTC, pajlada commented
I've let this become stale for long enough that it's not something I'm comfortable implementing right now, given the turbulence with chat over EventSub chat & Helix message sending

2024-03-17 11:26 UTC, closed without merging