Fix leading space in first user link in /mods and /vips
Chatterino/chatterino2 pull request #3349
Opened 2021-11-12 11:23 UTC by Mm2PL

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

Closes #3345

2021-11-12 13:16 UTC, Felanbird requested changes

2021-11-12 13:16 UTC, Felanbird commented on src/providers/twitch/TwitchMessageBuilder.cpp
> +    builder->emplace<TextElement>(prefix + " ", MessageElementFlag::Text,
```suggestion
    builder->emplace<TextElement>(prefix, MessageElementFlag::Text,
```

![image](https://user-images.githubusercontent.com/41973452/141472706-a44a8735-73a8-4ab1-bea8-90ac54724d58.png) - current
vs
![image](https://user-images.githubusercontent.com/41973452/141472558-60bdea83-f71c-40c7-a202-37a53432d11d.png) - change

2021-11-12 13:16 UTC, Felanbird commented on CHANGELOG.md
> +- Bugfix: Fixed the first link being broken in `/mods` and `/vips` (#3349)
```suggestion
- Bugfix: Fixed the first usercard being broken in `/mods` and `/vips` (#3349)
```

2021-11-12 13:56 UTC, Felanbird approved these changes
Functionality works as intended. 👍

2021-11-13 10:52 UTC, pajlada approved these changes

2021-11-13 11:11 UTC, merged