Updated contribution guide to include exemptions to the parameters
Chatterino/chatterino2 pull request #3530
Opened 2022-01-21 07:38 UTC by ALazyMeme

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

In certain cases, a parameter is required; whilst also being optional. The response returned should indicate that a parameter is required in order to get the desired outcome on the usage of a command. For example, `/streamlink` is a valid command, in order to open a specific channel; you MUST use the channel parameter, thus making it required: `/streamlink <channel>`

2022-01-21 07:46 UTC, Felanbird commented
This is my counter argument ce873aeb241cfca2e540165ae49626b7270a3816
![image](https://user-images.githubusercontent.com/41973452/150487017-e26e0c12-314b-4580-9232-aeb36b048c28.png)

2022-01-21 08:04 UTC, sando commented
This change seems unnecessarily pedantic - in the current example in CONTRIBUTING.md with the listed conventions, `/streamlink <channel>` implies that I *do* need to specify an argument for the command to work at all which is not the case. `/streamlink [channel]` implies that the argument isn't required for use, but *can* be specified for a change in default behaviour. 

@Felanbird's commit makes more sense to me.

2022-01-21 08:28 UTC, ALazyMeme commented
> This change seems unnecessarily pedantic - in the current example in CONTRIBUTING.md with the listed conventions, `/streamlink <channel>` implies that I _do_ need to specify an argument for the command to work at all which is not the case. `/streamlink [channel]` implies that the argument isn't required for use, but _can_ be specified for a change in default behaviour.
> 
> @Felanbird's commit makes more sense to me.

My commit does not oppose felanbird's. Both are technically correct and I believe both should be merged.

2022-01-21 12:56 UTC, zneix requested changes
In [utility argument convention](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html) it's all explained - an argument is put in angle brackets if invoking a command WITHOUT it results in an error. Invoking `/streamlink` with no arguments succeeds, which makes `[channel]` an OPTIONAL argument, not REQUIRED one.

> Felanbird's commit makes more sense to me.

agreed :+1: although where is that commit made to

2022-01-21 22:33 UTC, ALazyMeme commented
> Invoking `/streamlink` with no arguments succeeds, which makes `[channel]` an OPTIONAL argument, not REQUIRED one.

The usage text would only appear if the user somehow types the wrong thing as the channel parameter. Since we are trying to correct the user's actions, it is a required parameter - as they are wanting to open another channel, not open the current channel in streamlink.

I mention again that my commit is not designed to oppose felanbird's - as using `/streamlink [channel]` in the documentation IS correct. If the user is trying to open streamlink for another channel, then the channel parameter becomes required in order to get the desired result.

2022-01-21 23:00 UTC, Felanbird commented
One point of note only semi-relevant to this discussion, I believe the usage for `/streamlink` can never be generated because we don't check the input for said command. 
![image](https://user-images.githubusercontent.com/41973452/150610950-5d6cf85f-7d90-4249-9d7f-9c898138ce02.png)

2022-01-22 10:07 UTC, KillPainHaters commented
I love Chatterino, but does anyone know how to get the Chatterino Special Pepe Badge. lol 😋

2022-01-22 12:39 UTC, pajlada commented
CONTRIBUTING.md is not meant to be for users of Chatterino, but to help developers know when to use what type of brackets. Angled brackets imply that the parameter MUST be there, not that the parameter may be there, and if it's not there it will work with a default behaviour anyway.

Because of this, in #3536 I'm updating the usage documentation of streamlink, which was wrong.
Note that I am **not** changing the text in CONTRIBUTING.md because again, **it is not for users**. We could add texts after the example commands with the intent, but that can be another pull request.

Closing in favour of #3536

2022-01-22 12:39 UTC, closed without merging