Fix links with no thumbnail having previous link's thumbnail
Chatterino/chatterino2 pull request #3720
Opened 2022-05-08 20:32 UTC by qooq69

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description
Fixes  #1971

2022-05-15 06:28 UTC, Felanbird approved these changes
Functionality works as intended. 👍
before:
![image](https://user-images.githubusercontent.com/41973452/168460197-e085444f-ac55-465d-a559-8e795bc086df.png)

after:
![image](https://user-images.githubusercontent.com/41973452/168460161-f1bd43e2-3486-40b9-84f0-17813f47b879.png)

2022-05-22 10:40 UTC, zneix approved these changes
works

2022-05-22 10:49 UTC, pajlada requested changes
Other than this nitpick, looks good

2022-05-22 10:49 UTC, pajlada commented on src/providers/LinkResolver.cpp
>                          Image::fromUrl({root.value("thumbnail").toString()});
```suggestion
                if (root.contains("thumbnail"))
                {
                    thumbnail =
                        Image::fromUrl({root.value("thumbnail").toString()});
                }
```

2022-05-22 10:49 UTC, pajlada approved these changes

2022-05-22 11:16 UTC, merged