Removed total views from the usercard
Chatterino/chatterino2 pull request #3792
Opened 2022-06-02 00:32 UTC by mmattbtw

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description
Twitch removed the 'total views' counter from the channel page, dashboard, and I am certain the number isn't being updated anymore. [Announcement of total views being deprecated](https://discuss.dev.twitch.tv/t/get-users-api-endpoint-view-count-deprecation/37777)

2022-06-02 00:56 UTC, neil-lobo commented
https://discuss.dev.twitch.tv/t/get-users-api-endpoint-view-count-deprecation/37777

2022-06-02 01:15 UTC, iProdigy commented
Also consider removing the field from the underlying data models

2022-06-04 14:42 UTC, pajlada requested changes
Please remove the now unused `ui_.viewCountLabel` member in `UserInfoPopup`
Also remove the `viewCount` member from the model

2022-06-04 14:42 UTC, pajlada commented on CHANGELOG.md
> +- Bugfix: Removed total views from the usercard. (#3792)
Not a bugfix, should be classified as a Minor change

2022-06-05 11:33 UTC, pajlada approved these changes

2022-06-05 19:02 UTC, iProdigy approved these changes

2022-06-05 20:28 UTC, Felanbird commented on CHANGELOG.md
> +- Minor: Removed total views from the usercard. (#3792)
```suggestion
- Minor: Removed total views from the usercard, as Twitch no longer updates the number. (#3792)
```
sneaking in a quick blame towards Twitch so we don't get blamed 🙂

2022-06-05 20:31 UTC, Felanbird approved these changes

2022-06-05 20:51 UTC, merged