Harden emote parsing
Chatterino/chatterino2 pull request #3885
Opened 2022-07-30 11:23 UTC by pajlada

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

Messages I tested with

#### START OUT OF RANGE
`/fakemsg @emotes=84608:9-10 :test!test@test.tmi.twitch.tv PRIVMSG #pajlada :foo bar`

#### SINGLE CHARACTER EMOTE
`/fakemsg @emotes=84608:0-0 :test!test@test.tmi.twitch.tv PRIVMSG #pajlada :foo bar`

#### TWO CHARACTER EMOTE
`/fakemsg @emotes=84608:0-1 :test!test@test.tmi.twitch.tv PRIVMSG #pajlada :foo bar`

#### END OUT OF RANGE
`/fakemsg @emotes=84608:0-15 :test!test@test.tmi.twitch.tv PRIVMSG #pajlada :foo bar`

#### RANGE BAD
`/fakemsg @emotes=84608:15-2 :test!test@test.tmi.twitch.tv PRIVMSG #pajlada :foo bar`

#### MESSAGE FROM KARL-POLICE
`/fakemsg @badge-info=;badges=glhf-pledge/1;client-nonce=5d2627b0cbe56fa05faf5420def4807d;color=#1E90FF;display-name=oldcoeur;emote-only=1;emotes=84608:0-7;first-msg=1;flags=;id=7412fea4-8683-4cc9-a506-4228127a5c2d;mod=0;room-id=62300805;subscriber=0;tmi-sent-ts=1623429859222;turbo=0;user-id=139147886;user-type= :oldcoeur!oldcoeur@oldcoeur.tmi.twitch.tv PRIVMSG #test :test`

To test with these messages, join #test and #pajlada

Fixes #3487

Not adding a changelog entry as it doesn't fix an actual user-discoverable bug

2022-09-01 09:38 UTC, Mm2PL requested changes
I haven't tested yet in my c2. Would be nice if errors/malformed emotes had some kind of log and didn't fail silently. Also tests make sense for this.

2022-09-03 11:55 UTC, pajlada commented
I haven't added a test for the `            // Emote coords are out of range from the modified character positions` error case because I can't figure out a fake message for it

2022-09-04 11:11 UTC, pajlada commented
Issue with tests failing has to do with the `MockApplication` class symbols being merged/broken somehow - the fix is to put it in an anonymous namespace, making sure no other build object has access to it.

Will push a fix when another PR has been merged into the main branch

2022-09-04 11:59 UTC, pajlada commented
Tests should work now :-)

2022-11-04 20:27 UTC, Felanbird commented on src/providers/twitch/TwitchMessageBuilder.cpp
> +        auto occurences = parameters.at(1).split(',');
Can the other `occurence` spelling mistakes be corrected or is it already too late?

2022-11-04 21:37 UTC, Felanbird commented on src/providers/twitch/TwitchMessageBuilder.cpp
> +            vec.push_back(std::move(emoteOccurence));
here too if possible🙂

2022-11-05 10:04 UTC, merged