feat: add settings to toggle BTTV/FFZ global/channel emotes
Chatterino/chatterino2 pull request #3935
Opened 2022-08-25 20:00 UTC by Nerixyz

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

In preparation to adding 7TV support, which users should be able to turn off, this PR adds settings to turn toggle BTTV/FFZ global/channel emotes.

2022-08-25 20:25 UTC, Felanbird commented
nice good PR

2022-08-26 11:19 UTC, Nerixyz commented
I noticed some clang-tidy warnings (outside of my changes but in files I changed). I'm not sure if the clang-tidy CI would suggest fixes, so I'll list them here:

**Duplicate include:**
This include
https://github.com/Chatterino/chatterino2/blob/112fded341669a6fca4c6b066cb26eb9543de32e/src/singletons/Settings.hpp#L443-L445
will mark the includes at the top as duplicates
https://github.com/Chatterino/chatterino2/blob/112fded341669a6fca4c6b066cb26eb9543de32e/src/singletons/Settings.hpp#L3-L16

I don't really get why the include of the header itself is there in the first place.

And 
<details><summary>Missing braces around if-statements</summary>

  * https://github.com/Chatterino/chatterino2/blob/112fded341669a6fca4c6b066cb26eb9543de32e/src/providers/bttv/BttvEmotes.cpp#L138-L139
  * https://github.com/Chatterino/chatterino2/blob/112fded341669a6fca4c6b066cb26eb9543de32e/src/providers/bttv/BttvEmotes.cpp#L156-L158
  * https://github.com/Chatterino/chatterino2/blob/112fded341669a6fca4c6b066cb26eb9543de32e/src/providers/bttv/BttvEmotes.cpp#L200-L201
  * https://github.com/Chatterino/chatterino2/blob/112fded341669a6fca4c6b066cb26eb9543de32e/src/providers/bttv/BttvEmotes.cpp#L205-L207
  * https://github.com/Chatterino/chatterino2/blob/112fded341669a6fca4c6b066cb26eb9543de32e/src/providers/ffz/FfzEmotes.cpp#L178-L179
  * https://github.com/Chatterino/chatterino2/blob/112fded341669a6fca4c6b066cb26eb9543de32e/src/providers/ffz/FfzEmotes.cpp#L199-L201
  * https://github.com/Chatterino/chatterino2/blob/112fded341669a6fca4c6b066cb26eb9543de32e/src/providers/ffz/FfzEmotes.cpp#L256-L257
  * https://github.com/Chatterino/chatterino2/blob/112fded341669a6fca4c6b066cb26eb9543de32e/src/providers/ffz/FfzEmotes.cpp#L261-L263

</details>

2022-08-27 12:56 UTC, pajlada requested changes
Just some nitpicks, functionality looks good

I'd like to consider how the settings are presented to the user, but I don't have any super clear ideas for how it should look so I would be fine to defer that to a future update instead of blocking this one while we ideate.

2022-08-27 12:56 UTC, pajlada commented on src/providers/twitch/TwitchIrcServer.hpp
> +    void reloadAllFfzChannelEmotes();
Capitalize `BTTV` and `FFZ`

2022-08-27 12:56 UTC, pajlada commented on src/singletons/Settings.hpp
> +    BoolSetting ffzChannelEmotes = {"/emotes/ffzChannel", true};
Store the settings one level further down, e.g. `/emotes/bttv/global` and `/emotes/ffz/channel`
I would also consider adding some verbiage in at least the setting variable like `load...` or `...Enabled` or `enable...`

2022-08-28 06:07 UTC, Felanbird approved these changes
Functionality seems to work as I would expect it to 👍

2022-08-28 10:20 UTC, pajlada approved these changes

2022-08-28 10:20 UTC, merged