Implement initial support for RTL languages
Chatterino/chatterino2 pull request #3958
Opened 2022-09-08 22:11 UTC by mohad12211

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

![image](https://user-images.githubusercontent.com/51754973/189234734-ac12d791-6149-481d-9cfc-b53c2d4dfd51.png)

This is a dirty fix for RTL languages.
I don't have much experience with C++, the code is not well-structured and not optimized, but it is a try.
- Selection do not work yet.
- punctuation marks do not work for some reason.

this differs from #1970 by:
- mixing RTL and LTR does seem to work.
- line breaks also work.

should be a slightly better temporary fix, please tell me if there are more issues other than the ones I mentioned. I will try to fix the remaining issues and refactor the code after that, any help/tips on how to structure the code are very appreciated!

2022-09-08 23:15 UTC, Mm2PL commented on src/messages/layouts/MessageLayoutContainer.cpp
> +        if (this->elements_[i]->getText().isRightToLeft())
clang-tidy, what the fuck are you on

2022-09-09 16:48 UTC, mohad12211 commented
The last commit should show proper mixing between RTL and LTR, Twitch is doing it the wrong way actually.
If the text starts with an RTL word (e.g. Arabic), with LTR in the middle, it will only swap the RTL sequences, which is wrong, and a frustrating issue on Twitch... Should be working here. And it makes emotes show in the correct way as well.
Example: 
![image](https://user-images.githubusercontent.com/51754973/189400550-f1f90f22-d8f5-4338-b503-4d782b048493.png)

2022-09-09 22:38 UTC, Felanbird commented
The artifacts to test these changes can be found here, incase any issues can be found by native RTL speakers.

![image](https://user-images.githubusercontent.com/41973452/189454689-3c7d4654-cc6d-4dd2-8ce8-56ac08ec1259.png)

2022-09-14 08:02 UTC, EndlessJest commented
thank you so much! Everything seems to work correctly so far.

2022-09-16 20:10 UTC, Felanbird commented
From a functionality standpoint, it appears these changes push the "space" when using large emotes to the bottom, instead of the top of the message.

before:
![image](https://user-images.githubusercontent.com/41973452/190724795-4dbdfe5c-e113-4f67-a5fc-ad2a0b005a2b.png)

after:
![image](https://user-images.githubusercontent.com/41973452/190724729-5fb735cc-2fb7-48a7-b4fc-ee1558c1efee.png)

2022-09-16 21:30 UTC, mohad12211 commented
@Felanbird yes that was due to a weird thing I did, fixed after this refactor.

2022-09-16 21:42 UTC, mohad12211 commented
I refactored the fix a bit.

What is done is basically this:
we call  `_addElement` normally, once we if we detect an RTL word in the container, we reorder the elements.
we call `addElement` on each element again, without adding the element to `this->elements_`, if the text starts with an RTL word, we render from right to left (so `currentX_` will decrease instead of increase), otherwise render normally since we are calling `_addElement` in the correct order. since we need the previous element for Compact-Emotes, I pass the index for the previous element, I pass -2 by default, so that in the first call we just do it the old way, the second call it will start from -1.
I think this is better than making two `_addElement` functions, one for RTL and one for LTR with 90% similar code.
let me know if I can do it in a better way.

2022-09-17 03:17 UTC, Felanbird commented
![image](https://user-images.githubusercontent.com/41973452/190838539-cbf66328-6023-4480-8451-27d53b1ea236.png)
Top portion is this PR - bottom is normal chatterino incorrect rendering

2022-10-31 17:20 UTC, mohad12211 commented
Everything should be working now except selection, copying the entire message works for now as an alternative to selection.
I will see what I can do about selection soon.
Please test this as much as possible, preferably with other RTL languages other than Arabic.
To download the app with this changes. go to Checks, at the top, then build, then at the bottom you will find binaries for all operating systems:
![image](https://user-images.githubusercontent.com/51754973/199069008-25fcad07-e497-4a75-9907-71eecc3725ff.png)
![image](https://user-images.githubusercontent.com/51754973/199069085-3eb5b92e-d07e-48ef-bfb3-e1e60e78f926.png)

2022-11-05 12:19 UTC, pajlada requested changes

2022-11-05 12:19 UTC, pajlada commented on src/messages/layouts/MessageLayoutContainer.cpp
> +            this->reorderRTL(4);
Add comment here for what the 4 means

2022-11-05 12:19 UTC, pajlada commented on src/messages/layouts/MessageLayoutContainer.hpp
> +    void _addElement(MessageLayoutElement *element, bool forceAdd = false,
Could you incorporate your comment from here https://github.com/Chatterino/chatterino2/pull/3958#issuecomment-1249849323 to this function?

2022-11-05 12:19 UTC, pajlada commented on src/messages/layouts/MessageLayoutContainer.hpp
> +    void reorderRTL(int firstTextIndex);
Brief comment here how the function achieves its goal, and what `firstTextIndex` is used for

2022-11-05 12:19 UTC, pajlada commented on src/util/Helpers.cpp
> +    const QRegularExpression re("\\p{L}");
Can make this static

```suggestion
    static const QRegularExpression re("\\p{L}");
```

2022-11-10 18:53 UTC, mohad12211 commented
ready for final review & merge.

2022-11-10 19:26 UTC, pajlada commented
Looks like this for me (left = your PR, right = master)
![image](https://user-images.githubusercontent.com/962989/201187796-6b965904-5896-46ac-8915-b355e1f2c0ad.png)

Testing with this text: `a یک دو سه b`

2022-11-10 19:28 UTC, pajlada commented
When switching to Segoe UI it looks correct to me

![image](https://user-images.githubusercontent.com/962989/201188376-0b4a4fe8-d6f4-411c-9266-c82ca7f02f6c.png)

2022-11-10 19:34 UTC, pajlada commented
I attribute the previous errors I ran into to bad fonts on Linux

2022-11-10 19:40 UTC, Felanbird approved these changes
As far as I believe I can test this as someone who does not speak/write an RTL language, I believe it works.

2022-11-10 20:12 UTC, pajlada approved these changes
Thank you!!

2022-11-10 20:36 UTC, merged

2022-11-10 20:36 UTC, Felanbird commented
@mohad12211 Thanks for your contribution! As a first-time contributor, you can now add yourself to the contributors list that's shown inside the application.

To do so, open a new PR where you modify the resources/contributors.txt file and add yourself to the list. Make sure to read the comments at a top for instructions.