Improve Appearance of Reply Curve
Chatterino/chatterino2 pull request #4077
Opened 2022-10-22 01:14 UTC by dnsge

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

Improves the overall appearance of the reply curve. 

1. Uses linear horizontal and vertical parts with a curve in the top left (much like discord)
2. Fully extends downwards to the element below

<img width="449" alt="Screen Shot 2022-10-21 at 9 13 38 PM" src="https://user-images.githubusercontent.com/24928223/197309935-38a16207-e1ea-4e4b-a124-01c658c373ef.png">

2022-10-22 08:53 UTC, pajlada commented on src/messages/layouts/MessageLayoutElement.hpp
> +    ReplyCurveLayoutElement(MessageElement &creator, int width, float thickness,
good job clang-tidy!

2022-10-22 08:55 UTC, pajlada commented on src/messages/layouts/MessageLayoutElement.hpp
> +    virtual ~VerticalExpandingMessageLayoutElement() = default;
perfectly reasonable clang-tidy

2022-10-22 09:01 UTC, pajlada commented on src/messages/layouts/MessageLayoutContainer.cpp
> +        int yShift;
this one is ok

2022-10-22 09:18 UTC, pajlada requested changes
The curve looks great, but the change to compact emotes needs to be undone. It's fine if the setting is removed, since it's on by default and unconfigurable but the logic for compact emotes must stay.

https://user-images.githubusercontent.com/962989/197331621-76bd4784-77cf-452b-b369-76b5f67e60ed.mp4

2022-10-22 18:21 UTC, dnsge commented
> The change to compact emotes needs to be undone

I returned the compact emote rendering logic. Didn't realize that the setting was enabled by default 😅

2022-10-23 08:14 UTC, pajlada requested changes
I feel like this change is a bit too complex for what it gives, let's maybe start with only changing the curve of the line and work on the layout changes at another point - Sorry for the back-and-forth

The compactEmotes setting removal can still stay

2022-11-02 03:15 UTC, dnsge commented
I've gone ahead and removed the vertically expanding element stuff so that this PR now only includes adjustments to the shape of the reply curve itself.

New Appearance:
<img width="383" alt="Screen Shot 2022-11-01 at 11 00 49 PM" src="https://user-images.githubusercontent.com/24928223/199386944-b1d97206-58ee-4376-974a-dbd9a84edb46.png">

If anyone is interested in playing around with the curve parameters, you can modify the constants here:
https://github.com/dnsge/chatterino2/blob/feat/better-reply-curve/src/messages/MessageElement.cpp#L687-L690

2022-11-02 08:19 UTC, pajlada approved these changes

2022-11-02 08:19 UTC, pajlada commented
Thank you! :bow:

2022-11-02 08:19 UTC, merged