feat: Add Live Emote Updates for BTTV
Chatterino/chatterino2 pull request #4147
Opened 2022-11-13 13:50 UTC by Nerixyz

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

Same as 7TV. Waiting on BTTV in night/betterttv#5740 and Chatterino/twitch-pubsub-server-test#33.

2022-12-24 10:22 UTC, pajlada commented
I don't want personal emotes, but it seems like a prerequisite for using their live emote updates.
This PR in the current state doesn't implement personal emotes despite it seeming to be a requirement

2023-01-15 19:00 UTC, Felanbird commented
@Nerixyz can you resolve conflicts for this? Makes more sense for you to do it than me since https://github.com/Chatterino/chatterino2/pull/4275 is the culprit 🙂

2023-01-15 21:39 UTC, Felanbird approved these changes
Functionality works as expected 👍 - alias tooltip will come in a followup PR

2023-01-20 21:58 UTC, pajlada requested changes
Code quality wise this looks great, thank you for working on this!
I have not tested this yet but will do so tomorrow so I might

2023-01-20 21:58 UTC, pajlada commented on src/providers/bttv/BttvEmotes.hpp
> +        const BttvLiveUpdateEmoteRemoveMessage &message);
Can the `map` parameter and/or comments be updated to clarify that this function modifies channel specific emotes?

2023-01-20 21:58 UTC, pajlada commented on src/providers/bttv/BttvEmotes.hpp
> +        const BttvLiveUpdateEmoteUpdateAddMessage &message);
Can the `map` parameter and/or comments be updated to clarify that this function modifies channel specific emotes?

2023-01-20 21:58 UTC, pajlada commented on src/providers/bttv/BttvEmotes.hpp
> +        const BttvLiveUpdateEmoteUpdateAddMessage &message);
Can the `map` parameter and/or comments be updated to clarify that this function modifies channel specific emotes?

2023-01-20 21:58 UTC, pajlada commented on .github/workflows/test.yml
> +  TWITCH_PUBSUB_SERVER_IMAGE: ghcr.io/chatterino/twitch-pubsub-server-test:master
TODO: UPDATE THIS TO `v1.0.6` WHEN I'VE MADE THIS RELEASE

2023-01-21 09:58 UTC, pajlada approved these changes

2023-01-21 13:47 UTC, pajlada approved these changes

2023-01-21 14:06 UTC, merged