refactor: Clear Up Confusing Highlight Sound Settings
Chatterino/chatterino2 pull request #4194
Opened 2022-11-27 13:45 UTC by Nerixyz

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

As discussed in #1540, this clears up the highlight settings for sounds:

![](https://user-images.githubusercontent.com/19953266/193056731-6e9fc94d-1c7a-4483-8ae6-999025c75f3e.png)

<details><summary>Without custom/default sound</summary>

![](https://user-images.githubusercontent.com/19953266/193057157-96a31f5f-6518-4061-ac26-6bb10b4abd9e.png)

Closes #1540.

2022-11-27 14:25 UTC, kornes commented
suggestions:
- icon on clear button looks off, makes whole button kinda stands out too much. I would opt to remove it, or leave just icon, but then some variation of bin 🗑 would fit better i think.
- disable clear button when no custom sound is set
- maybe change current filename-only label, into input field with full file path, where user could paste/inspect path without clicking Change button. "Chatterino Ping" could be placeholder then.

2022-11-27 15:18 UTC, 8thony commented
Things I noticed:
- If you have set a custom sound in the table before and then click to change the sound but hit the cancel button in the file browser, a ticked checkbox stays in the table. (Is this checkbox even necessary?)
- The table entry with no option to play a sound doesn't block the option to set a custom sound.

2022-11-27 17:13 UTC, Nerixyz commented
> * icon on clear button looks off, makes whole button kinda stands out too much. I would opt to remove it, or leave just icon, but then some variation of bin 🗑 would fit better i think.

Removed.

> * disable clear button when no custom sound is set

It's hidden now.

> * maybe change current filename-only label, into input field with full file path, where user could paste/inspect path without clicking Change button. "Chatterino Ping" could be placeholder then.

This doesn't really fit the other settings. A user can now click on the path to open a file.

> * If you have set a custom sound in the table before and then click to change the sound but hit the cancel button in the file browser, a ticked checkbox stays in the table. (Is this checkbox even necessary?)

I removed the checkbox since it wasn't used.

> * The table entry with no option to play a sound doesn't block the option to set a custom sound.

There were actually settings for the sound-urls. But they weren't used, so I removed them.

2022-12-03 11:02 UTC, 8thony commented
If you set a sound with a long file name in the "Custom Sound" column and restart the program, the "Pattern" column becomes relatively narrow

If a sound with a long file name is set as "default sound", the settings window becomes wider

If you try this yourself, then make sure not to test the points above at the same time

2022-12-03 11:25 UTC, pajlada requested changes
Changing sounds doesn't update, it requires a restart

2022-12-03 11:25 UTC, pajlada commented on src/singletons/Settings.hpp
> +    //    BoolSetting customHighlightSound = {"/highlighting/useCustomSound", false};
Remove the setting entirely

```suggestion
```

2022-12-03 11:25 UTC, pajlada commented on src/messages/SharedMessageBuilder.cpp
> +        // or if the file doesn't exist.
Let's move this comment to above the function instead and describe what the function does

2022-12-03 13:19 UTC, Nerixyz commented
> If you set a sound with a long file name in the "Custom Sound" column and restart the program, the "Pattern" column becomes relatively narrow (Tested with 40 characters, including file extension)

Should be twice the width now, though this should really be changed after #3690.

> If a sound with a long file name is set as "default sound", the settings window becomes wider (Tested with 80 characters, including file extension)

Filenames are now truncated to 50 characters.

2022-12-03 15:18 UTC, 8thony commented
> Should be twice the width now, though this should really be changed after #3690.

It doesn't change anything for me, but it seems to be a general issue that isn't unique to this settings page.

> Filenames are now truncated to 50 characters.

It's okay. Maybe it shouldn't be limited to a certain number but to the current size of the window. So making it wider reveals more of the name. I'll let you decide what is better.

2022-12-03 15:33 UTC, pajlada approved these changes

2022-12-03 16:01 UTC, merged