Fix selection clearing not working in Reply window
Chatterino/chatterino2 pull request #4218
Opened 2022-12-06 21:29 UTC by kornes

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

Currently Reply window is missing behaviour of main chatterino window, where selection in splitInput and channelView cancels each other. 

PR changes:
- SplitInput will now expose `SplitInput::selectionChanged` signal, instead of doing any clearing locally 
- moved `ChannelView::selectionChanged` signal to Qt for consistency 
- use both signals in Reply window where it was missing

2022-12-06 22:26 UTC, pajlada requested changes
Please undo the changes related to `moved ChannelView::selectionChanged signal to Qt for consistency` unless you have some other reasoning for it

2022-12-07 01:22 UTC, kornes commented
Main reasoning for this change was to have handling of both signals use same solution since they are next to each other, personally i prefer Qt because its connect() better show both sides of connection and improve readability.
With Qt overall progress and Qt6 bringing new nice things like one-shot connections, imo we should encourage using native solution in new code and fallback to alternative only when there is benefit.
And finally, while not really in scope, this change doesn't have side effects as changed signal is used just in this 1 place.

If my excuses didn't convince you, im fine with reverting it, $notify me or let me know here :D

2022-12-07 08:43 UTC, pajlada commented
Yeah please undo the change for now, can review at some other point

2022-12-07 17:54 UTC, pajlada approved these changes

2022-12-07 18:21 UTC, merged