Add even more tooltips when hovering settings
Chatterino/chatterino2 pull request #4230
Opened 2022-12-12 18:46 UTC by Felanbird

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

I believe I remembered to test every setting, to make sure nothing like #4225 happens again 🦒

2022-12-16 19:35 UTC, Mm2PL requested changes

2022-12-16 19:35 UTC, Mm2PL commented on src/widgets/settingspages/GeneralPage.cpp
> +        "be closed by right-clicking or CTRL+SHIFT+W");
This tooltip should mention the defaultness of this or preferably use HotkeyController::getDisplaySequence introduced in #4045:

https://github.com/Chatterino/chatterino2/pull/4045/files#diff-d39bf5472005a5ba68ffdb09e75289913c7f1dd9b0285fd6acd44c799ac6771dR77-R86

2022-12-16 19:35 UTC, Mm2PL commented on src/widgets/settingspages/GeneralPage.cpp
> +                       "Adds a red underline below the most recent message "
Line color is configurable, having this mention red even when it's not certain might be confusing.

2022-12-16 19:35 UTC, Mm2PL commented on src/widgets/settingspages/GeneralPage.cpp
> +            "testaccount_420(테스트계정420) -> 테스트계정420");
Could you add the option value names to this? Not sure if users would know what a localized name is, maybe this could be better explained?

2022-12-17 12:06 UTC, pajlada requested changes
Small things

2022-12-17 15:58 UTC, Felanbird commented on src/widgets/settingspages/GeneralPage.cpp
> +                       "indicate they are live.");
![image](https://user-images.githubusercontent.com/41973452/208250466-b00c2e2f-a1a2-43f0-bb5e-27f0279f614a.png)

This is the name I have but I don't like it, as this name sounds like it toggles on the entire live functionality in Chatterino

2022-12-17 20:41 UTC, pajlada approved these changes

2022-12-18 11:30 UTC, merged