Use `CMakeDeps` as Generator on Conan
Chatterino/chatterino2 pull request #4335
Opened 2023-01-28 16:51 UTC by Nerixyz

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

The [`cmake`](https://docs.conan.io/en/latest/reference/generators/cmake.html) generator is marked as deprecated - [`CMakeDeps`](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmakedeps.html) and [`CMakeToolchain`](https://docs.conan.io/en/latest/reference/conanfile/tools/cmake/cmaketoolchain.html) are recommended. This PR migrates to the `CMakeDeps` generator.

### Migration Notes

0. Make sure you're using at least version 1.33 (Jan-2021).
1. Rerun `conan install`
2. You can remove `-DUSE_CONAN` from your CMake arguments.

2023-01-28 16:55 UTC, Nerixyz commented on CMakeLists.txt
> +# `OPTIONAL` is required, because conan doesn't set `boost_random_FOUND`.
I'll mention https://github.com/conan-io/conan-center-index/issues/11085 here.

2023-01-28 17:53 UTC, pajlada approved these changes
Looks good to me, let me know when you're ready to have this merged in :+1:

2023-01-29 12:45 UTC, pajlada requested changes

2023-01-29 12:45 UTC, pajlada commented on .github/workflows/build.yml
> +          conan profile update conf.tools.cmake.cmaketoolchain:generator=Ninja default
Change generator back to NMake

2023-01-29 12:45 UTC, pajlada commented on .github/workflows/build.yml
> +        uses: ilammy/msvc-dev-cmd@v1.12.0
Move this back to under `Install dependencies` unless you figure out this is actually necessary

2023-01-29 12:59 UTC, pajlada approved these changes

2023-01-29 13:10 UTC, merged