Initial implementation of filter type validation
Chatterino/chatterino2 pull request #4364
Opened 2023-02-11 05:33 UTC by dnsge

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

This PR adds type-checking to filters. For example, the filter `channel.name == "forsen" && author.badges contains "moderator"` can be deduced to evaluate to the type `Bool`. This allows us to tell the user why their filter is not working. Before, attempting to perform invalid operations like `String - Int` would silently fail while the filter would purport validity.

This PR was primarily motivated by witnessing conversations in Discord where users were confused about why apparently-valid filters weren't working. Additionally, this PR separates the parsing and execution of filters so the filtering language can be easily used in other parts of Chatterino (if another use-case comes up).

This PR also adjusts some (useless) semantics (for example, `5 + "2"` no longer `== 7` nor `== "7"`), so the wiki will require some minor updates.

_Most of the code change comes from splitting Expressions into multiple files. `synthesizeType()` is the primary addition in that realm._

## Example of detecting type errors

Consider the filter `message.content contains ("hello" || "goodbye")`. Someone could conceivably believe this filter allows messages that contain either "hello" or "goodbye" (in fact, this example was taken from Discord). Of course, we can't compute the logical or of two strings, so this filter would silently fail. 

Now, the filters page reports that there was an issue with the filter, and opening the detailed output gives:
<img width="453" alt="image" src="https://user-images.githubusercontent.com/24928223/218241866-d3d98af6-d17d-4b55-8cd4-977fdbcc26e7.png">

2023-02-18 06:34 UTC, dnsge commented on src/controllers/filters/lang/Filter.cpp
> +        if (channel && !channel->isEmpty() && tc)
wow! clang-tidy knows that `tc->isLive()` always evaluates to `false`!

2023-04-07 08:39 UTC, pajlada requested changes
I'm not super fond of how the `PossibleType` class is set up, could we utilize a variant there instead? I think the variant `operator==` forwards it to the contained class so it should still be easy to make the API easy to use.

Thank you for the inclusion of the tests - this looks good overall, there's most likely going to be another round or two of small nitpicks that are found as I dig more into this feature.

2023-04-07 08:39 UTC, pajlada commented on src/controllers/filters/lang/Filter.hpp
> +static const QMap<QString, Type> messageTypingContext = {
I'd prefer if this is `MESSAGE_TYPING_CONTEXT` too (rare clang-tidy agree), alongside a small comment explaining this

2023-04-07 08:39 UTC, pajlada commented on src/controllers/filters/lang/Filter.hpp
> +    {"message.length", Type::Int}};
```suggestion
    {"message.length", Type::Int},
};
```

Comma at the end for easier diffing in the future

2023-04-07 08:39 UTC, pajlada commented on src/controllers/filters/lang/Filter.hpp
> +using FilterResult = std::variant<Filter, FilterError>;
I'm fine with this :+1:

2023-04-07 22:21 UTC, dnsge commented on src/controllers/filters/lang/Filter.cpp
> +FilterResult Filter::fromString(const QString &str)
literally invalid to put static here but thanks

`error: 'static' can only be specified inside the class definition`

2023-04-07 23:19 UTC, dnsge commented
> I'm not super fond of how the PossibleType class is set up, could we utilize a variant there instead? I think the variant operator== forwards it to the contained class so it should still be easy to make the API easy to use.

I went ahead and reimplemented `PossibleType` to make use of `std::variant` internally (which ends up being much cleaner) in [5474c93](https://github.com/Chatterino/chatterino2/pull/4364/commits/5474c93e2e4b99c40101d3d969ed091d25a0e039). 

However, I feel like your comment was more suggesting replacing `PossibleType` altogether, e.g. 
```cpp
using PossibleType = std::variant<Type, IllTyped>;
``` 
This of course would be possible, but I thought that having a wrapper class would still be useful to have utility methods like `string()` and even `well()`, given the lovely syntax for checking variants (`std::holds_alternative<Type>(variant)`).

If you'd like it to make use of only a variant instead of a wrapper, I can implement that.

2023-04-08 06:56 UTC, pajlada commented
I'm fine with both `IllTyped` & `PossibleType` being classes as they will definitely have some member functions that help them be used, my thinking was more along the lines of:
```c++
using PossibleType = std::variant<TypeClass, IllTyped>;

class TypeClass {
  public:
    QString string() const;
    Type unwrap() const;

    bool operator==(Type) const;
    bool operator==(TypeClass) const;
    bool operator==(IllTyped) const;

  private:
  Type type_;
};

class IllTyped {
  public:
    QString description() const;

    bool operator==(Type) const;
    bool operator==(TypeClass) const;
    bool operator==(IllTyped) const;
};
```

Then in places where we've previously checked `if !possibleType.well() { print(possibleType.illTypedDescription()); }` we'd instead first unwrap it to either a `TypeClass` or `IllTyped`

Happy to hear your thoughts on that sort of solution - I can't see a downside to it but it might become apparent when it's actually done & used :dancers:

2023-04-08 18:39 UTC, dnsge commented
Updated to use `std::variant` directly :+1:

2023-04-09 10:22 UTC, pajlada approved these changes
Looks good to me :+1:

@dnsge if you can take a look at the changes I've made, we can get this merged in

2023-04-09 21:19 UTC, dnsge commented
@pajlada Everything looks good 👍

2023-04-09 21:35 UTC, merged