Dim Disabled Items in the Input Context-Menu
Chatterino/chatterino2 pull request #4423
Opened 2023-03-01 18:46 UTC by Nerixyz

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

The items in the context-menu, that shows up when right-clicking the input, all had the same text color. Some of them are usually disabled and when you hover over them, they don't change their background color. This PR dims the disabled items:

| Theme/State | White | Light | Dark | Black |
| --- | --- | --- | --- | --- |
| Before | ![2023-03-01_19-33-43](https://user-images.githubusercontent.com/19953266/222234981-6beb6506-1418-477d-ae4a-72c66c1a9dcc.png) | ![chatterino_2023-03-01_19-33-31](https://user-images.githubusercontent.com/19953266/222235048-9975402d-3e27-4284-b566-160d2e1f6697.png) | ![firefox_2023-03-01_19-30-50](https://user-images.githubusercontent.com/19953266/222235126-66382ef7-3ec3-4aa0-9ee2-65712bab2f2f.png) | ![firefox_2023-03-01_19-33-14](https://user-images.githubusercontent.com/19953266/222235167-346c08e0-e09c-40b3-bfff-e1d9c706af2e.png) |
| After | ![chatterino_2023-03-01_19-32-36](https://user-images.githubusercontent.com/19953266/222235227-64f53d74-3751-41f2-b949-0674fdabfde8.png) | ![chatterino_2023-03-01_19-32-23](https://user-images.githubusercontent.com/19953266/222235258-864bce8d-9a00-41ba-8acc-f34bfa2ea960.png) | ![chatterino_2023-03-01_19-30-36](https://user-images.githubusercontent.com/19953266/222235303-f9201f2d-da7e-4d0b-a3b4-272ef083730a.png) | ![firefox_2023-03-01_19-32-49](https://user-images.githubusercontent.com/19953266/222235368-02183a17-54e1-42be-afb1-93e6f6fe633c.png) |

2023-03-04 14:36 UTC, Felanbird approved these changes
Seems to work as I would expect it to 👍

2023-04-16 18:54 UTC, pajlada commented
I imagine this should just be settable by the theme itself? now that themes are JSON-bound

remove draft & poke me when it's ready for review again and I can take a look

2023-04-28 23:18 UTC, Wissididom reviewed
Just one thing I noticed

2023-04-28 23:18 UTC, Wissididom commented on CHANGELOG.md
> +- Bugfix: Fixed disabled items in context-menus having a weird or the default text color. (#4423)
```suggestion
- Bugfix: Fixed disabled items in context-menus having a weird text-effect or the default text color. (#4423)
```
Not sure if that suggestion would be correct, but I wanted to point out that it seems to me that there is a word missing

2023-04-29 08:03 UTC, Wissididom commented on CHANGELOG.md
> +- Bugfix: Fixed disabled items in context-menus having a weird or the default text color. (#4423)
When I think about it, it might even have been correct, if so, sorry

2023-04-29 16:00 UTC, pajlada requested changes
Regression: The "behind tab" background doesn't update automatically with this

2023-04-29 16:45 UTC, pajlada approved these changes
Works as expected on Linux

2023-04-29 16:50 UTC, merged