Cleanup `Theme`-related Code
Chatterino/chatterino2 pull request #4450
Opened 2023-03-16 14:29 UTC by Nerixyz

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

I mentioned this in #4447 at the beginning a bit: The theme code is hard to read and hard to maintain. This PR attempts to clean this code up (a bit at least). If you see more clean-up possibilities, let me know.

The commits should be reviewable on their own.

2023-03-16 18:17 UTC, pajlada requested changes
Small nitpick, overall looks good

2023-03-16 18:17 UTC, pajlada commented on src/singletons/Theme.cpp
> +    this->messages.selection = QColor::fromHsl(0, 0, isLight ? 0 : 255, 54);
Undo the change to `this->message.selection`

2023-03-16 18:17 UTC, pajlada commented on src/singletons/Theme.cpp
> +    this->splits.dropTargetRectBorder = QColor(0, 148, 255, 0);
Let's keep the light/dark theme colors of `dropTargetRect` even if their alpha is 0

2023-03-16 18:17 UTC, pajlada commented on src/singletons/Theme.cpp
> +        QColor::fromHslF(0, 0, isLight ? 0.5 : 0.24);
Undo change to `messageSeperator`

2023-03-17 19:07 UTC, pajlada approved these changes

2023-03-17 19:26 UTC, Mm2PL approved these changes
LGTM

2023-03-17 19:53 UTC, merged