Fix: check reply-parent-user-id for blocked user
Chatterino/chatterino2 pull request #4502
Opened 2023-04-01 22:29 UTC by 2547techno

Pull request checklist:

- [ ] `CHANGELOG.md` was updated, if applicable

# Description

WIP

Closes #4481 assuming option 1. from https://github.com/Chatterino/chatterino2/issues/4481#issuecomment-1493143358 .

If the message's reply parent user is blocked, ignore entire message.

2023-04-02 01:45 UTC, kornes commented
we shouldn't hide messages from non blocked users, 
personally i would go with censoring of reply context and replace it with some generic _"Blocked message"_

2023-04-02 20:42 UTC, 2547techno commented
> we shouldn't hide messages from non blocked users, personally i would go with censoring of reply context and replace it with some generic _"Blocked message"_

Make's sense, it now replaces the message content with \*blocked message\*.

Another option may be to treat the message as if the "show reply context" setting was disabled which probably follows closer to what blocking a user achieves normally. This made more sense after hearing: https://www.twitch.tv/videos/1782533448?t=01h10m21s

I'll leave the PR as draft for now.

2023-04-02 21:36 UTC, kornes commented
I think leaving reply context visible is better solution, because it let user know given message responds to blocked account and can be ignored right away. 
Question if username should be also removed from context, i would leave it but not sure if everyone would agree with that, so maybe axe it too?

2023-04-03 00:09 UTC, 2547techno commented
![image](https://user-images.githubusercontent.com/109011672/229386386-f2789c15-cd47-4a0d-85b6-863a5e98a587.png)
Reply context looks like this now.

Any other thoughts are welcome. Marking ready for review :)

2023-04-03 00:18 UTC, Felanbird commented
I'm putting in my vote for `[Blocked Message]` instead of `*Blocked Message*`

2023-04-05 01:21 UTC, 2547techno commented
![image](https://user-images.githubusercontent.com/109011672/229956945-a1f3a92b-44e5-41c4-8c26-3abada5e62e4.png)

2023-04-08 03:40 UTC, Felanbird approved these changes
Seems to work as expected, also tested replying to a block user just to make sure nothing crazy would happen, and that worked as expected as well.

2023-04-08 08:52 UTC, pajlada requested changes
Only a nitpick on the changelog entry, implementation looks good to me :+1:

2023-04-08 08:52 UTC, pajlada commented on CHANGELOG.md
> +- Bugfix: Fixed reply context showing blocked user's name & message (#4502)
Nitpicking, but this is not a bugfix. There's no expectation set for replies to a blocked user to be hidden or censored. Make this a Minor entry instead, and make sure there's a period at the end of the changelog entry (e.g. `- Minor: asd asd. (#4502)`

2023-04-13 15:31 UTC, Felanbird approved these changes
LGTM - only issue I would have would be making sure our native `show-blocked-messages-if-you're-a-mod` works, but I have a vague memory of testing that myself.

2023-04-13 16:13 UTC, merged

2023-04-13 16:16 UTC, Felanbird commented
@2547techno Thanks for your contribution! As a first-time contributor, you can now add yourself to the contributors list that's shown inside the application.

To do so, open a new PR where you modify the contributors.txt file and add yourself to the list. Make sure to read the comments at a top for instructions.