Consolidate input completion code in preparation for advanced completion strategies
Chatterino/chatterino2 pull request #4639
Opened 2023-05-16 04:52 UTC by dnsge

This PR looks to consolidate the input completion code which lives in `InputCompletionPopup` and `CompletionModel` into a single, extendible framework for sourcing and applying completions.

2023-05-19 12:13 UTC, pajlada reviewed
With a big change like this, tests and benchmarks are going to be extremely valuable.
Not just tests & benchmarks for the new code, but also for the old code. I think the approach for a big refactor like this, is going to be to modify the existing code to make it testable & benchmarkable, and then make the refactor, make sure all tests complete as expected (so the current behaviour **definitely** doesn't change), and that we don't slow things down by too much.

Abstraction wise, I would prefer to see less levels of abstraction. For AutocompleteSource for example, the `AutocompleteGenericSource` is something I'd like to see go away.
If this means sources like `AutocompleteEmoteSource` has to have an implementation that just calls a helper function, that's fine. I'd rather have a bit more c-v-paste than extra abstraction layers where possible

When it comes to tests, look at HighlightController to see how it provides highlights.
The potential lift with testing is that you would need to convert certain things to interfaces so they can be mockable in the first place. Emotes.hpp contains a mockable Emotes interface, so you can see how that's done for badges/commands etc

Overall the approach looks fine, will be easier to give proper feedback when we're aligned on code style/testing/benchmarks etc

2023-05-29 06:59 UTC, dnsge commented
After integrating the test cases from #4644, I discovered a couple discrepancies with the classic completion strategies which has been fixed in 85939eb.

Additionally, I realized that the tab completion was not respecting the `userCompletionOnlyWithAt` setting, which 
3f7a976 addressed.

With these being fixed, I feel the PR is now ready for a proper review.

2023-08-05 10:58 UTC, pajlada requested changes
Some formatting / structural things before I get into the meaty parts of the review

2023-08-05 10:58 UTC, pajlada commented on src/providers/autocomplete/AutocompleteModel.hpp
> +    AutocompleteModel(QObject *parent = nullptr);
Remove the default parameter, force users to specify nullptr if they really don't want to be the parent to this model

Make the constructor explicit if possible 
```suggestion
    AutocompleteModel(QObject *parent = nullptr);
```

2023-08-05 10:58 UTC, pajlada commented on src/providers/autocomplete/AutocompleteSources.cpp
> +#include "providers/autocomplete/AutocompleteSources.hpp"
Make a new directory for the CompletionSources and split each up into their own file

so we'd have:
 - `src/controllers/completion/sources/unified.hpp` + its cpp file
 - `src/controllers/completion/sources/commands.hpp`
 - `src/controllers/completion/sources/users.hpp`
 - etc...

2023-08-05 10:58 UTC, pajlada commented on src/providers/autocomplete/AutocompleteStrategy.hpp
> +#pragma once
Same as the sources, I'd like a new directory where each strategy has its own files

2023-08-05 10:58 UTC, pajlada commented on src/providers/autocomplete/AutocompleteSources.hpp
> +    AutocompleteEmoteSource(const Channel &channel,
This should just take a `const Channel *channel` - it currently goes from a shared_ptr<Channel>, gets deferenced to this reference, then internally gets referenced to a pointer

2023-08-05 11:06 UTC, pajlada commented
Overall, btw, this looks good and works as expected :+1: I don't expect there to be any big changes necessary

2023-09-24 11:34 UTC, pajlada approved these changes
Let's test this in nightly :+1: 
Thanks for putting in the effort!

2023-09-24 12:17 UTC, merged