Refactor tests and benchmarks
Chatterino/chatterino2 pull request #4700
Opened 2023-06-22 16:14 UTC by Nerixyz

# Description

This PR makes a few changes:

* Tests and benchmarks run on the main thread
  * This caused network tests to fail, since they rely on the Qt event-loop. These were adjusted to use [`qWaitFor`](https://doc.qt.io/qt-6/qtest.html#qWaitFor) which keeps the event-loop spinning. Since this is actually [declared in QtCore](https://github.com/qt/qtbase/blob/1a9ba8ee7d6d7cd624f5a299141bf4069a7cdeab/src/corelib/kernel/qtestsupport_core.h#L17-L52), no dependency to the Test component is necessary.
* Running benchmarks/tests related to emojis would segfault (at least for me with MSVC), because the `ImageExpirationPool` would be destroyed before the `Image` from `getEmpty` (the destructor calls `removeImagePtr`). The fix for this is a bit more involved, as it's [not trivial](https://stackoverflow.com/a/469613/16300717) to control the order of destruction of static inside functions. So the statics are moved inside an anonymous namespace. Creating a `ImageExpirationPool` when starting up will cause the `freeTimer_` to not work, as the main thread isn't running yet. That's why it's created lazily. For the emoji tests/benchmarks, this will cause `QObject::startTimer: Timers can only be used with threads started with QThread` to be printed after they're finished, because that's the first time the `ImageExpirationPool` is accessed (when destroying the empty image). This _can be_ fixed by e.g. calling `ImageExpirationPool::instance()` somewhere before/during the tests/benchmarks, but it's not really an issue **here**, since we're about to destroy the pool regardless (thus the timer would've never fired).
* The tests for filters failed on Qt 6 (filters are probably not fully working in Qt 6, so this could be a separate PR).
* https://httpbin.org was really slow for me at times, and sometimes it even timed out. I found https://postman-echo.com, which has the same API except for the special 402 status response.

Now the following is possible:

* Running _all_ tests in debug mode (this means that assertions will fire!).
* Using [`ctest`](https://cmake.org/cmake/help/book/mastering-cmake/chapter/Testing%20With%20CMake%20and%20CTest.html).

2023-06-22 17:26 UTC, Nerixyz reviewed
> and use ctest 

It doesn't actually use `ctest` - but it could: `ctest -j$(nproc) --output-on-failure` (optionally with `-T test`).

2023-06-22 17:27 UTC, Nerixyz commented on src/controllers/filters/lang/expressions/BinaryOperation.cpp
> +bool looselyCompareVariants(QVariant lhs, QVariant rhs)
I could do something like this (it would just use references, because of the `qSwap` call).

2023-06-24 09:37 UTC, pajlada requested changes

2023-06-24 09:37 UTC, pajlada commented on tests/src/NetworkRequest.cpp
> +        EXPECT_TRUE(QTest::qWaitFor([&requestDone] {
Keep condition variable, use wait_for and manually call https://github.com/qt/qtbase/blob/dev/src/corelib/kernel/qtestsupport_core.h#L33-L40

can make helper function if it feels cleaner

2023-06-24 09:37 UTC, pajlada commented on tests/src/NetworkRequest.cpp
> -        std::mutex mut;
rename this variable

2023-06-24 09:37 UTC, pajlada commented on tests/src/NetworkRequest.cpp
> +constexpr const bool CUSTOM_402_RESPONSE = false;
We can remove our test for the 402 code instead, and that should let us only replace the HTTPBIN base url

2023-06-24 09:37 UTC, pajlada commented on src/messages/Image.cpp
> +LazyExpirationPool globalImageExpirationPool;
I'd prefer if the ImageExpirationPool is just never free'd instead

2023-06-24 09:37 UTC, pajlada commented on src/controllers/filters/lang/expressions/BinaryOperation.cpp
> +namespace {
I'd prefer the qt6 & these fixes to be a separate PR

2023-06-24 13:01 UTC, pajlada approved these changes

2023-06-24 13:03 UTC, merged