Use WebSocket wrapper for all managers and clients
Chatterino/chatterino2 pull request #4723
Opened 2023-07-14 21:54 UTC by Nerixyz

# Description

As mentioned in https://github.com/Chatterino/chatterino2/issues/3452#issuecomment-1635860032, `websocketpp` causes slow compilation times. This PR attempts to combat this by encapsulating all `websocketpp` uses in a single translation unit (`providers/ws/Client.cpp`). Both PubSub and Liveupdates use this under the hood now.

2023-07-15 09:43 UTC, Nerixyz commented on src/providers/ws/Client.cpp
> +                      static_cast<qsizetype>(msg->get_payload().size())));
qt5 thing

2023-07-18 15:32 UTC, Nerixyz commented on src/providers/ws/Client.cpp
> +    std::shared_ptr<boost::asio::io_service::work> work_{nullptr};
This is deprecated. I should change it.

2023-07-29 10:43 UTC, pajlada requested changes
Same feedback on the pimpl stuff as the nativemessaging refactor, otherwise the idea is fine. will review more once the Q_Q's are gone

2023-07-30 10:21 UTC, pajlada requested changes
Small nitpicks, overall looks good :+1:

2023-07-30 10:21 UTC, pajlada commented on src/providers/ws/Client.cpp
> +
Assert that asioThread is not set

2023-07-30 10:21 UTC, pajlada commented on src/providers/ws/Client.cpp
> +
Assert that asioThread is set

2023-07-30 10:21 UTC, pajlada commented on src/providers/ws/Client.cpp
> +
Assert that asioThread is set

2023-07-30 10:21 UTC, pajlada commented on src/providers/ws/Client.cpp
> +        qCDebug(chatterinoLiveupdates)
Fix the logigng categories in the file

2024-03-17 11:45 UTC, Nerixyz commented
Gonna close this, since we're moving to eventsub which uses beast. We might want to have a wrapper around that (to reduce compilation time) in the future.

2024-03-17 11:45 UTC, closed without merging