Display all parsed elements when parsing emojis in replies
Chatterino/chatterino2 pull request #4875
Opened 2023-10-07 08:16 UTC by Nerixyz

# Description

Previously, only the first parsed element was used. This also adds a helper for Boost's and `std`'s `apply_visitor`/`visit`, which ensures all alternative types from the variants are handled.

Fixes #4874.

2023-10-07 08:48 UTC, Felanbird commented on CHANGELOG.md
> +- Bugfix: Fixed emojis getting lost in replies. (#4875)
```suggestion
- Bugfix: Fixed an issue where reply context didn't render correctly if an emoji was touching text. (#4875)
```

2023-10-07 08:49 UTC, Felanbird approved these changes
works on 🅱️ indows, unlucky for the other ones that didn't build

2023-10-07 09:39 UTC, Nerixyz commented
Seems like we _do_ need the deduction guidelines even though we're on C++ 20.

2023-10-08 09:38 UTC, pajlada requested changes
You can keep the Overloaded type, but since we have another big PR making changes here it'd be best if you just add the loop to fix the issue

2023-10-08 10:04 UTC, pajlada approved these changes

2023-10-08 10:09 UTC, merged