Added missing periods at mod-related messages and some system messages
Chatterino/chatterino2 pull request #5061
Opened 2024-01-01 15:32 UTC by fraxxio

Fixes #4515 

![Changes](https://github.com/Chatterino/chatterino2/assets/101990229/c3bf004b-336c-44fe-863c-859a48892c5b)

2024-01-01 15:43 UTC, pajlada requested changes
This should be handled on a per-message basis rather than checked in the SystemMessage constructor

2024-01-02 13:59 UTC, pajlada reviewed
Sorry, I should have been clearer in my initial feedback

The logic should be done where the message is actually created
As an example, the `USERNAME has cleared the chat` message is created at https://github.com/Chatterino/chatterino2/blob/65b1ed3/src/Application.cpp#L346-L361 so you'd want to just add the period to that specific message instead of inside MessageBuilder at all.
Preferably, when we're done, MessageBuilder.cpp should not have any changes

2024-01-03 08:14 UTC, pajlada requested changes
Some small nitpicks, otherwise looks good! This is what I meant

2024-01-03 08:14 UTC, pajlada commented on src/Application.cpp
> +                                action.target.login + ".");
Add the period directly to the QString instead of the login argument

2024-01-03 08:14 UTC, pajlada commented on src/controllers/commands/builtin/twitch/Announce.cpp
> +            "You must be logged in to use the /announce command!"));
Should be a period

2024-01-03 08:14 UTC, pajlada commented on src/controllers/commands/builtin/twitch/DeleteMessages.cpp
> +            QString("You must be logged in to use the %1 command!")
Should be a period

2024-01-03 08:14 UTC, pajlada commented on src/controllers/commands/builtin/twitch/ShieldMode.cpp
> +            QStringLiteral("You must be logged in to use the %1 command!")
Should be a period

2024-01-03 08:14 UTC, pajlada commented on src/providers/irc/AbstractIrcServer.cpp
> +    auto reconnected = makeSystemMessage("reconnected.");
Leave these two out of the change

2024-01-03 08:14 UTC, pajlada commented on src/providers/irc/IrcServer.cpp
> +                        shared->addMessage(makeSystemMessage("joined."));
Leave this out of the change

2024-01-03 08:14 UTC, pajlada commented on src/providers/irc/IrcServer.cpp
> +                        shared->addMessage(makeSystemMessage("parted."));
Leave this out of the change

2024-01-03 08:14 UTC, pajlada commented on src/providers/twitch/IrcMessageHandler.cpp
> +        twitchChannel->addMessage(makeSystemMessage("joined channel."));
Leave this out of the change

2024-01-03 08:14 UTC, pajlada commented on src/controllers/commands/builtin/twitch/StartCommercial.cpp
> +            "You must be logged in to use the /commercial command!"));
Should be a period

2024-01-03 08:14 UTC, pajlada commented on src/controllers/commands/builtin/twitch/Shoutout.cpp
> +            makeSystemMessage("You must be logged in to send shoutout!"));
Should be a period

2024-01-03 09:30 UTC, pajlada requested changes
Lastly, before this can be merged in, pull requests add a changelog entry in the `CHANGELOG.md` file.
This is a minor change, so it should be added under the `## Unversioned` category among the other `- Minor: ...` entries
A reasonable changelog entry for this change would be: `- Minor: Added missing periods at various moderator messages and commands. (#5061)`, although you're free to reword it a bit as you see fit

2024-01-03 09:30 UTC, pajlada commented on src/controllers/commands/builtin/twitch/UpdateColor.cpp
> +            "You must be logged in to use the /color command!"));
One last ! to ` conversion left, then it looks ready to merge!
I missed this one in my last review, sorry!

2024-01-03 09:32 UTC, fraxxio commented
Still missing periods on `/untimeout` `/ban` `/unban` commands responses, not sure where to add those.

2024-01-03 10:00 UTC, pajlada approved these changes
I fixed the `/ban`, `/untimeout`, and `/unban` responses now. They did have to be changed in their respective `MessageBuilder.cpp` code.

Thank you for your contribution!

2024-01-03 11:24 UTC, merged

2024-01-03 11:24 UTC, pajlada commented
Thank you! As a first-time contributor, you can now add yourself to the contributors list that's shown inside the About page in Chatterino.

If you want this, you can open a new PR where you modify the `resources/contributors.txt` file and add yourself to the list. Make sure to read the comments at the top for instructions.