Feature: add /announce[color] commands
Chatterino/chatterino2 pull request #5250
Opened 2024-03-13 20:02 UTC by 4rneee

This adds support to send the `/announce[color]` commands.  
Partially resolves https://github.com/Chatterino/chatterino2/issues/5218.  
Note that Chatterino currently does not support receiving colored highlights, so the color is currently only visible in the browser chat.

Screenshot:
![announce](https://github.com/Chatterino/chatterino2/assets/78976058/70ec39ec-d05d-40f9-86ee-98ae84ed1338)

2024-03-13 21:25 UTC, Mm2PL approved these changes
While I don't necessarily like having a ton of commands one for each color, this is how Twitch does it and commands are expected to work the mostly same on every client. 
Looks good to me.
I edited the PR description, so the issue wouldn't be closed when this is merged.

2024-03-13 21:51 UTC, pajlada requested changes
Some small nits, otherwise looks good to me

2024-03-13 21:51 UTC, pajlada commented on src/controllers/commands/builtin/twitch/Announce.cpp
> +                .arg(color == HelixAnnouncementColor::Primary ? "" : " ")));
nit: do an if on the color. this makes the message formatting cleaner & moves the colorStr logic into the same color check, something along the lines of
```
if color == Primary:
  msg = "Usage: /announce <message> - Call attention to your message with a highlight"
else:
  colorstr = magic_enum(...)
  msg = QString("Usage: /announce%1 <message> - Call attention to your message with a %1 highlight", colorstr)

ctx.channel->addMessage(makeSystemMessage(msg));
```

2024-03-13 21:51 UTC, pajlada commented on src/controllers/commands/builtin/twitch/Announce.cpp
> +QString sendAnnouncementColor(const CommandContext &ctx,
nit: move this function to an anon namespace, outsode if `namespace chatterino::commands`

so it'd be something along the lines of

```
namespace {
using namespace chatterino;
using namespace chatterino::commands; // maybe

QString sendAnnouncementColor...
```

2024-03-14 09:22 UTC, pajlada approved these changes

2024-03-14 19:36 UTC, merged