feat: show warning before blocking followed channel
Chatterino/chatterino2 pull request #5615
Opened 2024-10-02 09:43 UTC by Nerixyz

When blocking a followed channel, a warning is now shown about unfollowing that channel as a result of blocking them.

Closes https://github.com/Chatterino/chatterino2/discussions/5565.

2024-10-02 09:54 UTC, 8thony commented
Probably #1886 will be resolved as well

2024-10-06 09:13 UTC, pajlada requested changes

2024-10-06 09:13 UTC, pajlada commented on src/widgets/dialogs/UserInfoPopup.cpp
> +                    getApp()->getAccounts()->twitch.getCurrent()->getUserId(),
Let's have the messagebox always show up, regardless of follow state

2024-10-06 09:13 UTC, pajlada commented on src/providers/twitch/api/Helix.cpp
> +    QString userID, QString broadcasterID, const QObject *caller,
this change can stay

2024-10-06 09:13 UTC, pajlada commented on src/widgets/dialogs/UserInfoPopup.cpp
> +                            reenableBlockCheckbox();
Pressing "Cancel" will leave the checkbox toggled

2024-11-03 12:03 UTC, pajlada approved these changes

2024-11-03 12:29 UTC, merged