feat(plugins): add basic message construction
Chatterino/chatterino2 pull request #5754
Opened 2024-12-05 21:18 UTC by Nerixyz

This adds the API I described in https://github.com/Chatterino/chatterino2/discussions/4999#discussioncomment-11450186. There are minor differences (e.g. flags belong to a specific element).

The `/hello-world` example works with this implementation.

I have to add type definitions.

2025-05-10 12:18 UTC, pajlada requested changes
Just some nits, other than that this looks good.
Thank you!

2025-05-10 17:40 UTC, pajlada approved these changes
@Mm2PL merge this in when you've had a chance to take a look at it & you're happy with it

2025-07-24 22:15 UTC, Mm2PL requested changes
There are a few kinks to iron out, however the PR is looking pretty solid. Please update `docs/wip-plugins.md`.

2025-07-24 22:15 UTC, Mm2PL commented on docs/plugin-meta.lua
> +---@alias MessageColor "text"|"link"|"system"|string A color for a text element - "text" and "system" are special values that take the current theme into account
"link" does not take the theme into account?

2025-07-24 22:15 UTC, Mm2PL commented on scripts/make_luals_meta.py
> +To insert larger fragments of documentation, comments like
Please mention that its not allowed in a class body

2025-07-24 22:15 UTC, Mm2PL commented on src/controllers/plugins/api/Message.cpp
> +        tryMakeMessageColor(tbl.get<QString>("user_color")));
Invalid data or missing in these can explode our process.
Try:
```lua
ctx.channel:add_message(c2.Message.new({
    elements = {
        { type = 'mention' }
    }
}))
```

2025-07-24 22:15 UTC, Mm2PL commented on src/controllers/plugins/api/Message.cpp
> +    }
I can't make this work. Messages don't end up being highlighted.
```lua
ctx.channel:add_message(c2.Message.new({
    id = "thisisanid",
    highlight_color = "green",
    elements = {
        {
            type = "text",
            text = "Hello world!",
            color = "red"
        }
    }
}))
```

2025-07-24 22:15 UTC, Mm2PL commented on src/controllers/plugins/api/Message.cpp
> +    el->setTooltip(tbl.get_or("tooltip", QString{}));
You need to change logic at src/widgets/helper/ChannelView.cpp:2030 for this to work on all elements. Otherwise a visually empty tooltip will be displayed

2025-07-24 22:15 UTC, Mm2PL commented on src/controllers/plugins/api/Message.cpp
> +        tbl["text"], tbl.get_or("flags", MessageElementFlag::Text),
This could crash.

2025-07-24 22:15 UTC, Mm2PL commented on src/controllers/plugins/api/Message.cpp
> +        tbl["text"], tbl.get_or("flags", MessageElementFlag::Text),
This could crash.

2025-07-24 22:15 UTC, Mm2PL commented on src/controllers/plugins/api/Message.cpp
> +    QString type = tbl["type"];
This could crash.

2025-07-25 18:23 UTC, Nerixyz commented on src/controllers/plugins/api/Message.cpp
> +    }
This requires the `Highlighted` flag (see added example).

2025-07-31 13:28 UTC, Mm2PL approved these changes

2025-07-31 13:36 UTC, merged