change default local r9k keybinding per macOS standard
Chatterino/chatterino2 pull request #5764
Opened 2024-12-10 20:04 UTC by jacob-thompson

fixes #5711

#5711 is labelled as a bug, but this behavior is intended ([source](https://doc.qt.io/qt-6/qkeysequence.html)) ([source](https://support.apple.com/en-us/102650))

easiest fix is to change the default local r9k keymap. while `Ctrl`/`Cmd` + `H` is a more mnemonic keymap, I do not think it is mnemonic enough to be worth making all macOS users have to configure this setting manually.

2024-12-10 20:17 UTC, Nerixyz commented on src/controllers/hotkeys/HotkeyController.cpp
> +                            QKeySequence("Ctrl+."), "toggleLocalR9K",
This should be [`#ifdef Q_OS_MACOS`](https://doc.qt.io/qt-6/qtsystemdetection.html#Q_OS_MACOS)d.

2024-12-10 20:18 UTC, Mm2PL requested changes
<kbd>Ctrl+H</kbd> is a perfectly good bind for every other OS, I don't want it changed for any other system.

2024-12-10 20:18 UTC, Mm2PL commented on src/controllers/hotkeys/HotkeyController.cpp
>                              std::vector<QString>(), "toggle local r9k");
This does not change configs for existing users. This is probably not what should be done here as CMD+H is already reserved there is no harm forcing `toggle local r9k` to be rebound to it for every user.

2024-12-10 20:38 UTC, jacob-thompson commented
@Nerixyz @Mm2PL see changes

I don't have a windows machine to test with but this works on my end

2024-12-10 20:45 UTC, Nerixyz commented
> I don't have a windows machine to test with but this works on my end

This doesn't change anything on Windows or Linux, so it's fine. I don't know about common macOS key binds, so I can't comment on the chosen bind.

2024-12-10 20:52 UTC, jacob-thompson commented
I didn’t think a tremendous amount about the keymap, just settled on something that works and is easily pressable. The only other option I considered is `Cmd` + `,`, but this is already reserved to open the settings interface. I figured if something more mnemonic is considered in the future, this can always be changed again

From: nerix ***@***.***>
Date: Tuesday, December 10, 2024 at 12:45
To: Chatterino/chatterino2 ***@***.***>
Cc: Jacob Alexander Thompson ***@***.***>, Author ***@***.***>
Subject: Re: [Chatterino/chatterino2] change default local r9k keybinding per macOS standard (PR #5764)

I don't have a windows machine to test with but this works on my end

This doesn't change anything on Windows or Linux, so it's fine. I don't know about common macOS key binds, so I can't comment on the chosen bind.

—
Reply to this email directly, view it on GitHub<https://github.com/Chatterino/chatterino2/pull/5764#issuecomment-2532849527>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ALXQ5SFIV5UFS5ZUH5SUI432E5HIDAVCNFSM6AAAAABTL6HCJKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKMZSHA2DSNJSG4>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2025-01-19 10:22 UTC, pajlada requested changes
I agree that setting a hotkey to one of the macOS "system" bindings is wrong.

However, I think I would prefer to _not_ set a hotkey in this specific scenario for macOS, rather than adding a macOS-specific hotkey.
macOS users can still add a custom hotkey to the "toggle local r9k" action as they see fit.

2025-01-19 23:03 UTC, jacob-thompson commented
@pajlada 

> However, I think I would prefer to _not_ set a hotkey in this specific scenario for macOS, rather than adding a macOS-specific hotkey.

I agree that it is a bit silly to have one specific default hotkey be different for one specific subset of users. Still, I would argue that the given solution is best.

The only other "solution" I can think of at the moment that would address each of this PR's reviews would be to set the following attribute, which modifies Qt's default behavior of swapping `Control` with `Command` on macOS:

```
QCoreApplication::setAttribute(Qt::AA_MacDontSwapCtrlAndMeta);
```

However, this is a terrible solution, mainly because this affects existing configurations. It also presents the same exact issue that this PR aims to solve, as `Control+E` is also a [macOS system keybind](https://support.apple.com/en-us/102650).

> macOS users can still add a custom hotkey to the "toggle local r9k" action as they see fit.

Of course. They can do this whether the given solution is implemented or not. The issue that this PR aims to solve, though, is that macOS users are *forced* to configure this manually should they want to utilize this feature.

2025-01-20 08:43 UTC, pajlada commented
If this was a more used feature I would agree to consider a macOS binding for it, but adding it adds complexity to all future hotkeys that I want to avoid unless necessary

2025-03-21 16:27 UTC, pajlada commented
Feel free to re-open once you've made the requested changes

2025-03-21 17:43 UTC, jacob-thompson commented
> Feel free to re-open once you've made the requested changes

what were the requested changes? you claimed that this fix would create complications in the future (how?). I don't really see how it does that unless you plan on adding an absurd amount of hotkeys to this software that has only seen a couple new hotkeys in the last 3 years.

are we worried that we might think `Cmd/Ctrl+H` is a valid keybinding for macOS several years from now? that exact issue exists _right now_ #5711, and this PR is the fix for that issue.

2025-03-21 18:16 UTC, Felanbird commented
The requested change was to not set a hotkey for this setting on macOS, that way the conflict with `⌘H` wont exist in the future, and users who want it bound can bind it to what they like.

2025-03-21 18:27 UTC, pajlada commented
Yup, what Felanbird said. Sorry if I wasn't clear in my reviews

2025-03-21 19:55 UTC, jacob-thompson commented
oh okay, so no default hotkey for macos? I suppose that works. I have a commit ready that leaves the default hotkey blank for macOS, and `CTRL+H` for all other systems.

> Feel free to re-open once you've made the requested changes

I don't have the power to re-open, btw

2025-03-21 21:41 UTC, pajlada commented
@jacob-thompson Yup! Just no default hotkey for macOS

2025-03-21 22:28 UTC, pajlada approved these changes
This looks good from my perspective - I took the liberty of changing a few tiny things. Could you take a peek to make sure that the changes I made still align with your goals @jacob-thompson ?

Thanks!

2025-03-21 22:42 UTC, jacob-thompson commented
looks good 👍

2025-03-22 01:01 UTC, Mm2PL requested changes
Adding a hotkey without a key sequence requires more changes in the HotkeyController and EditHotkeyDialog.

2025-03-22 09:00 UTC, pajlada commented on src/controllers/hotkeys/HotkeyController.cpp
> +                            std::vector<QString>(), "toggle local r9k");
So the appropriate action is to not `tryAddDefault` at all?

2025-03-22 11:01 UTC, Mm2PL commented on src/controllers/hotkeys/HotkeyController.cpp
> +                            std::vector<QString>(), "toggle local r9k");
I believe so, yes

2025-03-22 14:41 UTC, Mm2PL approved these changes

2025-03-22 15:14 UTC, merged

2025-03-22 16:16 UTC, pajlada commented
Thank you @jacob-thompson! As a first-time contributor, you are now eligible to be listed in the About page in Chatterino.

If you want this, you can open a new PR where you modify the `resources/contributors.txt` file and add yourself to the list. Read the comments at the top for instructions.